import { appendFileSync, existsSync, mkdirSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import type { Diagnostic, WorkspaceInfo } from '@specbridge/core';
import { assertInsideWorkspace, writeFileAtomic } from '@specbridge/core';
import { OrchestrationError } from '../errors.js';
import type { JobCheckpoint, JobGraph, JobState } from './state.js';
import {
  JOB_STATE_SCHEMA_VERSION,
  jobCheckpointSchema,
  jobGraphSchema,
  jobStateSchema,
} from './state.js';
import type { JobEventType } from './vocabulary.js';

/**
 * Job persistence: `.specbridge/jobs/<jobId>/`.
 *
 *   job.json            the versioned job state (atomic, last-writer view)
 *   events.jsonl        append-only history
 *   graphs/<n>.json     every runtime-graph revision, kept forever
 *   agents/<name>.json  bounded structured agent results, append-only
 *   checkpoint.json     the latest structured checkpoint
 *
 * A separate namespace from `.specbridge/orchestration/` (the v1.1
 * interactive runs) so neither store can misread the other's records, and
 * from `.specbridge/runs/` (execution evidence), which jobs reference by id
 * exactly the way v1.1 runs do — evidence, verification, and completion stay
 * where they already live.
 *
 * Guarantees, all exercised by tests:
 *   - every path passes assertInsideWorkspace (no traversal, no symlink escape)
 *   - every job/graph/checkpoint write is atomic (temp + fsync + rename)
 *   - a corrupt or unknown-major-version record fails safely and is preserved
 *     for diagnosis, never silently rewritten or deleted
 *   - reads never mutate state
 *   - a workspace without a jobs directory behaves exactly like v1.0/v1.1
 */

export const JOBS_DIR_NAME = 'jobs';

/** Ids are generated by SpecBridge; the pattern is enforced on every path. */
const ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

/** Agent-result file names are generated by the store, never by callers. */
const AGENT_RESULT_NAME_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}\.json$/;

export function jobsRootDir(workspace: WorkspaceInfo): string {
  return path.join(workspace.sidecarDir, JOBS_DIR_NAME);
}

export function assertJobId(jobId: string): string {
  if (!ID_PATTERN.test(jobId)) {
    throw new OrchestrationError('SBO029', `Invalid job id "${jobId}".`, {
      remediation: ['Ids are generated by SpecBridge; pass one returned by a job operation.'],
    });
  }
  return jobId;
}

export function jobDir(workspace: WorkspaceInfo, jobId: string): string {
  assertJobId(jobId);
  return assertInsideWorkspace(workspace.rootDir, path.join(jobsRootDir(workspace), jobId));
}

function artifactPath(workspace: WorkspaceInfo, jobId: string, ...segments: string[]): string {
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(jobDir(workspace, jobId), ...segments),
  );
}

function majorOf(version: string): string {
  return version.split('.')[0] ?? '';
}

// ---------------------------------------------------------------------------
// Job state
// ---------------------------------------------------------------------------

export type JobReadResult =
  | { kind: 'ok'; job: JobState }
  | { kind: 'missing' }
  /** Present but unusable. The file is left exactly as found. */
  | { kind: 'corrupt'; problem: string; file: string }
  | { kind: 'unsupported-version'; version: string; file: string };

export function readJobState(workspace: WorkspaceInfo, jobId: string): JobReadResult {
  const file = artifactPath(workspace, jobId, 'job.json');
  if (!existsSync(file)) return { kind: 'missing' };
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(file, 'utf8'));
  } catch (cause) {
    return { kind: 'corrupt', problem: cause instanceof Error ? cause.message : String(cause), file };
  }
  const declared =
    parsed !== null && typeof parsed === 'object'
      ? (parsed as { schemaVersion?: unknown }).schemaVersion
      : undefined;
  if (typeof declared !== 'string') {
    return { kind: 'corrupt', problem: 'schemaVersion is missing', file };
  }
  if (majorOf(declared) !== majorOf(JOB_STATE_SCHEMA_VERSION)) {
    return { kind: 'unsupported-version', version: declared, file };
  }
  const result = jobStateSchema.safeParse(parsed);
  if (!result.success) {
    return {
      kind: 'corrupt',
      problem: result.error.issues
        .map((issue) => `${issue.path.join('.') || '(root)'}: ${issue.message}`)
        .join('; '),
      file,
    };
  }
  return { kind: 'ok', job: result.data };
}

/** Read a job or throw a stable SBO error explaining exactly what is wrong. */
export function requireJobState(workspace: WorkspaceInfo, jobId: string): JobState {
  const read = readJobState(workspace, jobId);
  switch (read.kind) {
    case 'ok':
      return read.job;
    case 'missing':
      throw new OrchestrationError(
        'SBO029',
        `Job "${jobId}" was not found under .specbridge/${JOBS_DIR_NAME}/.`,
        { remediation: ['List jobs with `specbridge orchestrate jobs --json`.'] },
      );
    case 'corrupt':
      throw new OrchestrationError(
        'SBO030',
        `Job "${jobId}" has unreadable state: ${read.problem}. The file was left untouched for diagnosis.`,
        {
          remediation: [
            `Inspect ${read.file}.`,
            'Create a new job; the corrupt record is never rewritten automatically.',
          ],
          details: { file: read.file },
        },
      );
    case 'unsupported-version':
      throw new OrchestrationError(
        'SBO030',
        `Job "${jobId}" was written by a newer SpecBridge (schema ${read.version}); ` +
          `this build reads ${JOB_STATE_SCHEMA_VERSION}.`,
        {
          remediation: ['Upgrade SpecBridge, or create a new job with this version.'],
          details: { file: read.file, version: read.version },
        },
      );
  }
}

export function writeJobState(workspace: WorkspaceInfo, job: JobState): JobState {
  const validated = jobStateSchema.parse(job);
  const dir = jobDir(workspace, validated.jobId);
  mkdirSync(dir, { recursive: true });
  writeFileAtomic(path.join(dir, 'job.json'), `${JSON.stringify(validated, null, 2)}\n`);
  return validated;
}

export function initializeJobRecord(workspace: WorkspaceInfo, job: JobState): JobState {
  const dir = jobDir(workspace, job.jobId);
  if (existsSync(dir)) {
    throw new OrchestrationError('SBO030', `Job directory already exists: ${dir}. Ids must be unique.`);
  }
  mkdirSync(path.join(dir, 'graphs'), { recursive: true });
  mkdirSync(path.join(dir, 'agents'), { recursive: true });
  return writeJobState(workspace, job);
}

export interface JobListResult {
  jobs: JobState[];
  diagnostics: Diagnostic[];
}

/** All jobs, newest first. Unreadable records become diagnostics. */
export function listJobs(workspace: WorkspaceInfo): JobListResult {
  const root = jobsRootDir(workspace);
  if (!existsSync(root)) return { jobs: [], diagnostics: [] };
  const jobs: JobState[] = [];
  const diagnostics: Diagnostic[] = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (!ID_PATTERN.test(entry.name)) continue;
    const read = readJobState(workspace, entry.name);
    if (read.kind === 'ok') {
      jobs.push(read.job);
      continue;
    }
    if (read.kind === 'missing') continue;
    diagnostics.push({
      severity: 'warning',
      code:
        read.kind === 'unsupported-version'
          ? 'JOB_STATE_UNSUPPORTED_VERSION'
          : 'JOB_STATE_UNREADABLE',
      message:
        read.kind === 'unsupported-version'
          ? `Job ${entry.name} uses state schema ${read.version}; ignoring it.`
          : `Job ${entry.name} has unreadable state; ignoring it.`,
      file: read.file,
    });
  }
  jobs.sort(
    (a, b) => b.createdAt.localeCompare(a.createdAt, 'en') || b.jobId.localeCompare(a.jobId, 'en'),
  );
  return { jobs, diagnostics };
}

// ---------------------------------------------------------------------------
// Graph revisions
// ---------------------------------------------------------------------------

/** Persist one graph revision. Revisions are append-only: nothing is replaced. */
export function storeGraphRevision(
  workspace: WorkspaceInfo,
  jobId: string,
  graph: JobGraph,
): { graph: JobGraph; file: string } {
  const validated = jobGraphSchema.parse(graph);
  const file = artifactPath(
    workspace,
    jobId,
    'graphs',
    `${String(validated.revision).padStart(4, '0')}.json`,
  );
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return { graph: validated, file };
}

export function readGraphRevision(
  workspace: WorkspaceInfo,
  jobId: string,
  revision: number,
): JobGraph | undefined {
  if (!Number.isInteger(revision) || revision < 1) return undefined;
  const file = artifactPath(workspace, jobId, 'graphs', `${String(revision).padStart(4, '0')}.json`);
  if (!existsSync(file)) return undefined;
  try {
    const result = jobGraphSchema.safeParse(JSON.parse(readFileSync(file, 'utf8')));
    return result.success ? result.data : undefined;
  } catch {
    return undefined;
  }
}

/** Read the active graph revision or throw a stable SBO error. */
export function requireGraphRevision(
  workspace: WorkspaceInfo,
  jobId: string,
  revision: number,
): JobGraph {
  const graph = readGraphRevision(workspace, jobId, revision);
  if (graph === undefined) {
    throw new OrchestrationError(
      'SBO031',
      `Graph revision ${revision} of job ${jobId} is missing or unreadable.`,
      { remediation: ['The job cannot continue without its graph; inspect the graphs/ directory.'] },
    );
  }
  return graph;
}

/** Every stored graph revision number, ascending (cheap; no parsing). */
export function listGraphRevisions(workspace: WorkspaceInfo, jobId: string): number[] {
  const dir = artifactPath(workspace, jobId, 'graphs');
  if (!existsSync(dir)) return [];
  const revisions: number[] = [];
  for (const name of readdirSync(dir).sort()) {
    if (!/^\d{4}\.json$/.test(name)) continue;
    revisions.push(Number.parseInt(name.slice(0, 4), 10));
  }
  return revisions;
}

// ---------------------------------------------------------------------------
// Node plans
// ---------------------------------------------------------------------------

/**
 * Persist one node-plan revision (a v1.1 ExecutionPlan document bound to the
 * node's approved task). Append-only, exactly like graph revisions.
 */
export function storeNodePlan(
  workspace: WorkspaceInfo,
  jobId: string,
  nodeId: string,
  revision: number,
  plan: Record<string, unknown>,
): { file: string } {
  if (!ID_PATTERN.test(nodeId)) {
    throw new OrchestrationError('SBO031', `Invalid node id "${nodeId}".`);
  }
  const file = artifactPath(
    workspace,
    jobId,
    'plans',
    `${nodeId}-${String(revision).padStart(4, '0')}.json`,
  );
  if (existsSync(file)) {
    throw new OrchestrationError('SBO031', `Plan revision ${revision} for node ${nodeId} already exists.`);
  }
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(plan, null, 2)}\n`);
  return { file };
}

export function readNodePlan(
  workspace: WorkspaceInfo,
  jobId: string,
  nodeId: string,
  revision: number,
): Record<string, unknown> | undefined {
  if (!ID_PATTERN.test(nodeId) || !Number.isInteger(revision) || revision < 1) return undefined;
  const file = artifactPath(
    workspace,
    jobId,
    'plans',
    `${nodeId}-${String(revision).padStart(4, '0')}.json`,
  );
  if (!existsSync(file)) return undefined;
  try {
    const parsed: unknown = JSON.parse(readFileSync(file, 'utf8'));
    return parsed !== null && typeof parsed === 'object'
      ? (parsed as Record<string, unknown>)
      : undefined;
  } catch {
    return undefined;
  }
}

// ---------------------------------------------------------------------------
// Agent results
// ---------------------------------------------------------------------------

/**
 * Persist one bounded structured agent result and return its reference.
 *
 * The caller passes an ALREADY-VALIDATED structured document (see
 * agents/contracts.ts); this layer enforces the size bound and the naming
 * scheme. Results are append-only: a name collision is refused, never
 * overwritten.
 */
export function storeAgentResult(
  workspace: WorkspaceInfo,
  jobId: string,
  name: string,
  document: Record<string, unknown>,
  limits: { maxBytes: number },
): { ref: string; file: string } {
  if (!AGENT_RESULT_NAME_PATTERN.test(name)) {
    throw new OrchestrationError('SBO037', `Invalid agent result name "${name}".`);
  }
  const serialized = `${JSON.stringify(document, null, 2)}\n`;
  if (Buffer.byteLength(serialized, 'utf8') > limits.maxBytes) {
    throw new OrchestrationError(
      'SBO037',
      `The agent result "${name}" exceeds the ${limits.maxBytes}-byte limit and was not stored.`,
      { remediation: ['Structured agent results are summaries; keep them bounded.'] },
    );
  }
  const file = artifactPath(workspace, jobId, 'agents', name);
  if (existsSync(file)) {
    throw new OrchestrationError('SBO037', `Agent result "${name}" already exists; results are append-only.`);
  }
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, serialized);
  return { ref: `agents/${name}`, file };
}

/** Read one stored agent result by its recorded reference. */
export function readAgentResult(
  workspace: WorkspaceInfo,
  jobId: string,
  ref: string,
): Record<string, unknown> | undefined {
  const name = ref.startsWith('agents/') ? ref.slice('agents/'.length) : ref;
  if (!AGENT_RESULT_NAME_PATTERN.test(name)) return undefined;
  const file = artifactPath(workspace, jobId, 'agents', name);
  if (!existsSync(file)) return undefined;
  try {
    const parsed: unknown = JSON.parse(readFileSync(file, 'utf8'));
    return parsed !== null && typeof parsed === 'object'
      ? (parsed as Record<string, unknown>)
      : undefined;
  } catch {
    return undefined;
  }
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

export interface JobEvent extends Record<string, unknown> {
  at: string;
  type: JobEventType;
}

/**
 * Append one bounded event. Oversized payloads are refused rather than
 * truncated, exactly like the v1.1 event log.
 */
export function appendJobEvent(
  workspace: WorkspaceInfo,
  jobId: string,
  event: JobEvent,
  limits: { maxEventBytes: number },
): void {
  const line = `${JSON.stringify(event)}\n`;
  if (Buffer.byteLength(line, 'utf8') > limits.maxEventBytes) {
    throw new OrchestrationError(
      'SBO021',
      `Job event of type "${event.type}" is larger than the configured ` +
        `${limits.maxEventBytes}-byte limit and was not recorded.`,
      { remediation: ['Record a shorter summary; full evidence lives in the run directory.'] },
    );
  }
  const file = artifactPath(workspace, jobId, 'events.jsonl');
  mkdirSync(path.dirname(file), { recursive: true });
  appendFileSync(file, line, 'utf8');
}

export interface JobEventPage {
  events: JobEvent[];
  total: number;
  truncated: boolean;
}

/** Read a bounded page of events, newest last. Never unbounded. */
export function readJobEvents(
  workspace: WorkspaceInfo,
  jobId: string,
  options: { limit?: number; offset?: number } = {},
): JobEventPage {
  const file = artifactPath(workspace, jobId, 'events.jsonl');
  if (!existsSync(file)) return { events: [], total: 0, truncated: false };
  let raw: string;
  try {
    raw = readFileSync(file, 'utf8');
  } catch {
    return { events: [], total: 0, truncated: false };
  }
  const lines = raw.split('\n').filter((line) => line.trim().length > 0);
  const parsed: JobEvent[] = [];
  for (const line of lines) {
    try {
      const value: unknown = JSON.parse(line);
      if (value !== null && typeof value === 'object') parsed.push(value as JobEvent);
    } catch {
      // A partially written final line (crash during append) is skipped, not
      // fatal: the rest of the history stays readable.
    }
  }
  const limit = Math.max(1, Math.min(options.limit ?? 50, 500));
  const offset = Math.max(0, options.offset ?? 0);
  const window = parsed.slice(Math.max(0, parsed.length - offset - limit), parsed.length - offset);
  return { events: window, total: parsed.length, truncated: parsed.length > window.length };
}

export function countJobEvents(workspace: WorkspaceInfo, jobId: string): number {
  const file = artifactPath(workspace, jobId, 'events.jsonl');
  if (!existsSync(file)) return 0;
  try {
    return readFileSync(file, 'utf8')
      .split('\n')
      .filter((line) => line.trim().length > 0).length;
  } catch {
    return 0;
  }
}

// ---------------------------------------------------------------------------
// Checkpoints
// ---------------------------------------------------------------------------

export function writeJobCheckpoint(
  workspace: WorkspaceInfo,
  jobId: string,
  checkpoint: JobCheckpoint,
): string {
  const validated = jobCheckpointSchema.parse(checkpoint);
  const file = artifactPath(workspace, jobId, 'checkpoint.json');
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return file;
}

export function readJobCheckpoint(
  workspace: WorkspaceInfo,
  jobId: string,
): JobCheckpoint | undefined {
  const file = artifactPath(workspace, jobId, 'checkpoint.json');
  if (!existsSync(file)) return undefined;
  try {
    const result = jobCheckpointSchema.safeParse(JSON.parse(readFileSync(file, 'utf8')));
    return result.success ? result.data : undefined;
  } catch {
    return undefined;
  }
}
