import { existsSync, mkdirSync, readFileSync, readdirSync, appendFileSync } from 'node:fs';
import path from 'node:path';
import type { WorkspaceInfo } from '@specbridge/core';
import { assertInsideWorkspace, writeFileAtomic } from '@specbridge/core';
import { AutonomyError } from './errors.js';

/**
 * Autonomy persistence:
 *
 *   .specbridge/autonomy/
 *     seals/<sealId>.json              immutable authorization snapshots
 *     bindings/<jobId>.json            job -> seal join
 *     supervisor/state.json            the supervisor registry
 *     supervisor/leases/<jobId>.json   one lease per supervised job
 *     supervisor/log.jsonl             append-only supervision actions
 *     preflight/<reportId>.json        overnight preflight reports
 *     toolsmith/<jobId>/<id>.json      capability requests and grants
 *     environments/plans/<planId>.json      environment plans
 *     environments/instances/<id>.json      environment instances
 *     environments/logs/<id>/<service>.log  retained diagnostics
 *     browser/<scenarioId>.json        browser scenario definitions
 *     browser/results/<resultId>.json  scenario results
 *     browser/evidence/<resultId>/...  screenshots, DOM, console
 *     critic/<critiqueId>.json         UX critiques
 *     closure/<jobId>/ledger.json      the contract closure ledger
 *     closure/<jobId>/audits/<id>.json closure audits
 *     repairs/<repairId>.json          control-plane repair records
 *     telemetry/<jobId>.json           the autonomy telemetry record
 *     certification/<runId>/...        zero-touch certification records
 *
 * Same guarantees as every other SpecBridge state family: every path passes
 * `assertInsideWorkspace`, every write is atomic, and a corrupt record is
 * skipped by listings and left on disk for diagnosis rather than rewritten.
 *
 * One rule specific to this family: SEALS ARE NEVER OVERWRITTEN. `writeSeal`
 * refuses an existing path outright rather than trusting callers to
 * remember. An authorization that can be edited in place is not an
 * authorization, it is a suggestion, and the whole vNext.10 authority model
 * rests on being able to say which one a job ran under.
 */

const ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

export function assertAutonomyId(kind: string, id: string): string {
  if (!ID_PATTERN.test(id)) {
    throw new AutonomyError('SBA024', `Invalid ${kind} id "${id}".`, {
      remediation: ['Ids are generated by SpecBridge; pass one returned by an autonomy operation.'],
      details: { kind, id },
    });
  }
  return id;
}

export function autonomyDir(workspace: WorkspaceInfo): string {
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(workspace.rootDir, '.specbridge', 'autonomy'),
  );
}

/** A path inside the autonomy family, validated against the workspace root. */
export function autonomyPath(workspace: WorkspaceInfo, ...segments: string[]): string {
  return assertInsideWorkspace(workspace.rootDir, path.join(autonomyDir(workspace), ...segments));
}

export function writeJsonRecord(file: string, value: unknown): void {
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(value, null, 2)}\n`);
}

/**
 * Read and parse one record, returning `undefined` when it is missing OR
 * unreadable OR fails validation.
 *
 * Swallowing the parse failure is deliberate and matches the rest of the
 * codebase: a corrupt autonomy record must not crash the report that exists
 * to explain what the runtime did. Callers that need the difference between
 * "absent" and "corrupt" use `readJsonRecordStrict`.
 */
export function readJsonRecord<T>(file: string, parse: (raw: unknown) => T): T | undefined {
  if (!existsSync(file)) return undefined;
  try {
    return parse(JSON.parse(readFileSync(file, 'utf8')));
  } catch {
    return undefined;
  }
}

export type RecordReadResult<T> =
  | { kind: 'ok'; value: T }
  | { kind: 'missing' }
  | { kind: 'invalid'; message: string };

export function readJsonRecordStrict<T>(
  file: string,
  parse: (raw: unknown) => T,
): RecordReadResult<T> {
  if (!existsSync(file)) return { kind: 'missing' };
  try {
    return { kind: 'ok', value: parse(JSON.parse(readFileSync(file, 'utf8'))) };
  } catch (cause) {
    return { kind: 'invalid', message: cause instanceof Error ? cause.message : String(cause) };
  }
}

/** List every parseable record in one directory, sorted by file name. */
export function listJsonRecords<T>(dir: string, parse: (raw: unknown) => T): T[] {
  if (!existsSync(dir)) return [];
  const out: T[] = [];
  for (const entry of readdirSync(dir).sort()) {
    if (!entry.endsWith('.json')) continue;
    const value = readJsonRecord(path.join(dir, entry), parse);
    if (value !== undefined) out.push(value);
  }
  return out;
}

/** Append one line to a JSONL log, creating the directory if needed. */
export function appendJsonl(file: string, value: Record<string, unknown>): void {
  mkdirSync(path.dirname(file), { recursive: true });
  appendFileSync(file, `${JSON.stringify(value)}\n`, 'utf8');
}

export interface JsonlPage<T> {
  entries: T[];
  /** Lines that failed to parse. Reported, never silently dropped. */
  skipped: number;
}

export function readJsonl<T>(file: string, parse: (raw: unknown) => T, limit = 5_000): JsonlPage<T> {
  if (!existsSync(file)) return { entries: [], skipped: 0 };
  const lines = readFileSync(file, 'utf8').split('\n').filter((line) => line.trim().length > 0);
  const slice = lines.slice(-limit);
  const entries: T[] = [];
  let skipped = 0;
  for (const line of slice) {
    try {
      entries.push(parse(JSON.parse(line)));
    } catch {
      skipped += 1;
    }
  }
  return { entries, skipped };
}

/**
 * Write a record that must not already exist.
 *
 * Used for seals and for anything else whose whole meaning depends on being
 * a fact about a moment rather than a mutable row.
 */
export function writeImmutableRecord(file: string, value: unknown, kind: string): void {
  if (existsSync(file)) {
    throw new AutonomyError('SBA024', `A ${kind} already exists at this identity and is immutable.`, {
      remediation: [
        `Create a new ${kind} that supersedes the existing one instead of rewriting history.`,
      ],
      details: { file: path.basename(file), kind },
    });
  }
  writeJsonRecord(file, value);
}
