import { existsSync, mkdirSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import type { WorkspaceInfo } from '@specbridge/core';
import { assertInsideWorkspace, writeFileAtomic } from '@specbridge/core';
import { OrchestrationError } from '../errors.js';
import { jobDir } from '../jobs/store.js';
import type { TaskAttempt, TaskCheckpoint } from './state.js';
import { taskAttemptSchema, taskCheckpointSchema } from './state.js';

/**
 * Survival-runtime persistence, inside the existing job namespace:
 *
 *   .specbridge/jobs/<jobId>/
 *     task-attempts/<attemptId>.json        durable ExecutionAttempts
 *     task-checkpoints/<nodeId>/<seq>.json  append-only structured checkpoints
 *
 * The same guarantees as every job artifact, exercised by tests:
 *   - every path passes assertInsideWorkspace
 *   - every write is atomic (temp + fsync + rename)
 *   - attempts and checkpoints are append-only at the record level: a new
 *     attempt or checkpoint gets a new file; finalizing an attempt updates
 *     its own record and nothing else; nothing is ever deleted
 *   - a corrupt record is skipped by listings and preserved for diagnosis,
 *     never rewritten
 *
 * This store is orchestration/runtime state. Git and the workspace remain
 * responsible for source-code state; run directories remain responsible for
 * raw execution evidence. Deleting every provider session and conversation
 * touches nothing here — that independence is the whole point.
 */

const ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

function assertRecordId(kind: 'attempt' | 'node', id: string): string {
  if (!ID_PATTERN.test(id)) {
    throw new OrchestrationError('SBO049', `Invalid ${kind} id "${id}".`, {
      remediation: ['Ids are generated by SpecBridge; pass one returned by a survival operation.'],
    });
  }
  return id;
}

export function taskAttemptsDir(workspace: WorkspaceInfo, jobId: string): string {
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(jobDir(workspace, jobId), 'task-attempts'),
  );
}

function taskAttemptFile(workspace: WorkspaceInfo, jobId: string, attemptId: string): string {
  assertRecordId('attempt', attemptId);
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(taskAttemptsDir(workspace, jobId), `${attemptId}.json`),
  );
}

export function taskCheckpointsDir(workspace: WorkspaceInfo, jobId: string, nodeId: string): string {
  assertRecordId('node', nodeId);
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(jobDir(workspace, jobId), 'task-checkpoints', nodeId),
  );
}

// ---------------------------------------------------------------------------
// Attempts
// ---------------------------------------------------------------------------

/** Persist a NEW attempt record. Refuses to overwrite an existing one. */
export function writeNewTaskAttempt(workspace: WorkspaceInfo, attempt: TaskAttempt): TaskAttempt {
  const validated = taskAttemptSchema.parse(attempt);
  const file = taskAttemptFile(workspace, validated.jobId, validated.attemptId);
  if (existsSync(file)) {
    throw new OrchestrationError(
      'SBO049',
      `Attempt ${validated.attemptId} already exists; attempts are append-only.`,
    );
  }
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return validated;
}

/**
 * Update an EXISTING attempt record in place (finalize, reconcile). The
 * record keeps its identity; the update is atomic; history stays intact
 * because finished attempts are never reopened (enforced in the service).
 */
export function updateTaskAttempt(workspace: WorkspaceInfo, attempt: TaskAttempt): TaskAttempt {
  const validated = taskAttemptSchema.parse(attempt);
  const file = taskAttemptFile(workspace, validated.jobId, validated.attemptId);
  if (!existsSync(file)) {
    throw new OrchestrationError(
      'SBO049',
      `Attempt ${validated.attemptId} does not exist; create it with writeNewTaskAttempt first.`,
    );
  }
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return validated;
}

export function readTaskAttempt(
  workspace: WorkspaceInfo,
  jobId: string,
  attemptId: string,
): TaskAttempt | undefined {
  const file = taskAttemptFile(workspace, jobId, attemptId);
  if (!existsSync(file)) return undefined;
  try {
    const parsed = taskAttemptSchema.safeParse(JSON.parse(readFileSync(file, 'utf8')));
    return parsed.success ? parsed.data : undefined;
  } catch {
    return undefined;
  }
}

export interface ListTaskAttemptsOptions {
  /** Restrict to one runtime node (task). */
  nodeId?: string | undefined;
  /** Restrict to one status. */
  status?: TaskAttempt['status'] | undefined;
}

/** All attempt records for a job, oldest first. Corrupt records are skipped. */
export function listTaskAttempts(
  workspace: WorkspaceInfo,
  jobId: string,
  options: ListTaskAttemptsOptions = {},
): TaskAttempt[] {
  const dir = taskAttemptsDir(workspace, jobId);
  if (!existsSync(dir)) return [];
  const attempts: TaskAttempt[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith('.json')) continue;
    try {
      const parsed = taskAttemptSchema.safeParse(
        JSON.parse(readFileSync(path.join(dir, entry.name), 'utf8')),
      );
      if (!parsed.success) continue;
      if (options.nodeId !== undefined && parsed.data.nodeId !== options.nodeId) continue;
      if (options.status !== undefined && parsed.data.status !== options.status) continue;
      attempts.push(parsed.data);
    } catch {
      // Unreadable records are preserved on disk and skipped here.
    }
  }
  attempts.sort(
    (a, b) =>
      a.startedAt.localeCompare(b.startedAt, 'en') || a.attemptId.localeCompare(b.attemptId, 'en'),
  );
  return attempts;
}

/** Next attempt number for a node: one past the highest recorded. */
export function nextAttemptNumber(workspace: WorkspaceInfo, jobId: string, nodeId: string): number {
  const attempts = listTaskAttempts(workspace, jobId, { nodeId });
  return attempts.reduce((max, attempt) => Math.max(max, attempt.attemptNumber), 0) + 1;
}

// ---------------------------------------------------------------------------
// Checkpoints
// ---------------------------------------------------------------------------

/** Persist one checkpoint revision. Append-only: an existing seq is refused. */
export function writeTaskCheckpoint(
  workspace: WorkspaceInfo,
  checkpoint: TaskCheckpoint,
): { checkpoint: TaskCheckpoint; file: string } {
  const validated = taskCheckpointSchema.parse(checkpoint);
  const dir = taskCheckpointsDir(workspace, validated.jobId, validated.nodeId);
  const file = assertInsideWorkspace(
    workspace.rootDir,
    path.join(dir, `${String(validated.seq).padStart(4, '0')}.json`),
  );
  if (existsSync(file)) {
    throw new OrchestrationError(
      'SBO050',
      `Checkpoint seq ${validated.seq} for node ${validated.nodeId} already exists; checkpoints are append-only.`,
    );
  }
  mkdirSync(dir, { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return { checkpoint: validated, file };
}

/** Every stored checkpoint seq for a node, ascending (cheap; no parsing). */
export function listTaskCheckpointSeqs(
  workspace: WorkspaceInfo,
  jobId: string,
  nodeId: string,
): number[] {
  const dir = taskCheckpointsDir(workspace, jobId, nodeId);
  if (!existsSync(dir)) return [];
  const seqs: number[] = [];
  for (const name of readdirSync(dir).sort()) {
    if (!/^\d{4}\.json$/.test(name)) continue;
    seqs.push(Number.parseInt(name.slice(0, 4), 10));
  }
  return seqs;
}

export function readTaskCheckpoint(
  workspace: WorkspaceInfo,
  jobId: string,
  nodeId: string,
  seq: number,
): TaskCheckpoint | undefined {
  if (!Number.isInteger(seq) || seq < 1) return undefined;
  const dir = taskCheckpointsDir(workspace, jobId, nodeId);
  const file = path.join(dir, `${String(seq).padStart(4, '0')}.json`);
  if (!existsSync(file)) return undefined;
  try {
    const parsed = taskCheckpointSchema.safeParse(JSON.parse(readFileSync(file, 'utf8')));
    return parsed.success ? parsed.data : undefined;
  } catch {
    return undefined;
  }
}

/**
 * The latest VALID checkpoint for a node — the resume point. A corrupt
 * newest revision falls back to the newest readable one: resume prefers
 * honest older truth over unreadable newer bytes.
 */
export function readLatestTaskCheckpoint(
  workspace: WorkspaceInfo,
  jobId: string,
  nodeId: string,
): TaskCheckpoint | undefined {
  const seqs = listTaskCheckpointSeqs(workspace, jobId, nodeId);
  for (let index = seqs.length - 1; index >= 0; index -= 1) {
    const seq = seqs[index];
    if (seq === undefined) continue;
    const checkpoint = readTaskCheckpoint(workspace, jobId, nodeId, seq);
    if (checkpoint !== undefined) return checkpoint;
  }
  return undefined;
}
