import { appendFileSync, existsSync, mkdirSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import type { Diagnostic, WorkspaceInfo } from '@specbridge/core';
import { assertInsideWorkspace, writeFileAtomic } from '@specbridge/core';
import { MissionError } from './errors.js';
import type {
  ContractChangeRequest,
  ConversationTurn,
  DiscoveryDecision,
  DiscoveryQuestion,
  MissionAdr,
  MissionCheckpoint,
  MissionConstitution,
  MissionCoverage,
  MissionFact,
  MissionState,
  ProductContract,
} from './state.js';
import {
  MISSION_STATE_SCHEMA_VERSION,
  contractChangeRequestSchema,
  conversationTurnSchema,
  discoveryDecisionSchema,
  discoveryQuestionSchema,
  missionAdrSchema,
  missionCheckpointSchema,
  missionConstitutionSchema,
  missionCoverageSchema,
  missionFactSchema,
  missionStateSchema,
  productContractSchema,
} from './state.js';
import type { MissionEventType } from './vocabulary.js';

/**
 * Mission persistence: `.specbridge/missions/<missionId>/`.
 *
 *   mission.json          the versioned mission state (atomic, last-writer view)
 *   events.jsonl          append-only history
 *   conversation.jsonl    append-only visible discovery turns
 *   facts.jsonl           append-only fact records; current view folds by id
 *   questions.jsonl       append-only question records; current view folds by id
 *   decisions.jsonl       append-only decision records; current view folds by id
 *   coverage.json         the computed coverage snapshot (atomic rewrite)
 *   constitution.json     the constitution (atomic rewrite; rules keep history in-file)
 *   adrs/ADR-####.json    immutable ADR files
 *   contracts/CTR-####-r###.json  immutable per-revision contract files
 *   ccrs/CCR-####.json    contract change requests (service-controlled rewrites)
 *   spec-candidates/      synthesized stage candidates + provenance map
 *   checkpoint.json       the latest structured checkpoint
 *
 * Guarantees, all exercised by tests:
 *   - every path passes assertInsideWorkspace (no traversal, no symlink escape)
 *   - every JSON write is atomic (temp + fsync + rename)
 *   - jsonl histories are append-only; corrections append superseding records
 *   - a corrupt or unknown-major-version record fails safely and is preserved
 *     for diagnosis, never silently rewritten or deleted
 *   - reads never mutate state
 *   - `.kiro` is never touched: mission state is runtime metadata and lives
 *     entirely inside the `.specbridge` sidecar
 */

export const MISSIONS_DIR_NAME = 'missions';

/** Ids are generated by SpecBridge; the pattern is enforced on every path. */
const ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

export function missionsRootDir(workspace: WorkspaceInfo): string {
  return path.join(workspace.sidecarDir, MISSIONS_DIR_NAME);
}

export function assertMissionId(missionId: string): string {
  if (!ID_PATTERN.test(missionId)) {
    throw new MissionError('SBM001', `Invalid mission id "${missionId}".`, {
      remediation: ['Ids are generated by SpecBridge; pass one returned by a mission operation.'],
    });
  }
  return missionId;
}

export function missionDir(workspace: WorkspaceInfo, missionId: string): string {
  assertMissionId(missionId);
  return assertInsideWorkspace(workspace.rootDir, path.join(missionsRootDir(workspace), missionId));
}

function artifactPath(workspace: WorkspaceInfo, missionId: string, ...segments: string[]): string {
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(missionDir(workspace, missionId), ...segments),
  );
}

function majorOf(version: string): string {
  return version.split('.')[0] ?? '';
}

// ---------------------------------------------------------------------------
// Mission state
// ---------------------------------------------------------------------------

export type MissionReadResult =
  | { kind: 'ok'; mission: MissionState }
  | { kind: 'missing' }
  | { kind: 'corrupt'; problem: string; file: string }
  | { kind: 'unsupported-version'; version: string; file: string };

export function readMissionState(workspace: WorkspaceInfo, missionId: string): MissionReadResult {
  const file = artifactPath(workspace, missionId, 'mission.json');
  if (!existsSync(file)) return { kind: 'missing' };
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(file, 'utf8'));
  } catch (cause) {
    return { kind: 'corrupt', problem: cause instanceof Error ? cause.message : String(cause), file };
  }
  const declared =
    parsed !== null && typeof parsed === 'object'
      ? (parsed as { schemaVersion?: unknown }).schemaVersion
      : undefined;
  if (typeof declared !== 'string') {
    return { kind: 'corrupt', problem: 'schemaVersion is missing', file };
  }
  if (majorOf(declared) !== majorOf(MISSION_STATE_SCHEMA_VERSION)) {
    return { kind: 'unsupported-version', version: declared, file };
  }
  const result = missionStateSchema.safeParse(parsed);
  if (!result.success) {
    return {
      kind: 'corrupt',
      problem: result.error.issues
        .map((issue) => `${issue.path.join('.') || '(root)'}: ${issue.message}`)
        .join('; '),
      file,
    };
  }
  return { kind: 'ok', mission: result.data };
}

export function requireMissionState(workspace: WorkspaceInfo, missionId: string): MissionState {
  const read = readMissionState(workspace, missionId);
  switch (read.kind) {
    case 'ok':
      return read.mission;
    case 'missing':
      throw new MissionError(
        'SBM001',
        `Mission "${missionId}" was not found under .specbridge/${MISSIONS_DIR_NAME}/.`,
        { remediation: ['List missions with `specbridge mission status --json`.'] },
      );
    case 'corrupt':
      throw new MissionError(
        'SBM002',
        `Mission "${missionId}" has unreadable state: ${read.problem}. The file was left untouched for diagnosis.`,
        {
          remediation: [
            `Inspect ${read.file}.`,
            'Begin a new mission; the corrupt record is never rewritten automatically.',
          ],
          details: { file: read.file },
        },
      );
    case 'unsupported-version':
      throw new MissionError(
        'SBM002',
        `Mission "${missionId}" was written by a newer SpecBridge (schema ${read.version}); ` +
          `this build reads ${MISSION_STATE_SCHEMA_VERSION}.`,
        {
          remediation: ['Upgrade SpecBridge, or begin a new mission with this version.'],
          details: { file: read.file, version: read.version },
        },
      );
  }
}

export function writeMissionState(workspace: WorkspaceInfo, mission: MissionState): MissionState {
  const validated = missionStateSchema.parse(mission);
  const dir = missionDir(workspace, validated.missionId);
  mkdirSync(dir, { recursive: true });
  writeFileAtomic(path.join(dir, 'mission.json'), `${JSON.stringify(validated, null, 2)}\n`);
  return validated;
}

export function initializeMissionRecord(
  workspace: WorkspaceInfo,
  mission: MissionState,
): MissionState {
  const dir = missionDir(workspace, mission.missionId);
  if (existsSync(dir)) {
    throw new MissionError('SBM010', `Mission directory already exists: ${dir}. Ids must be unique.`);
  }
  mkdirSync(path.join(dir, 'adrs'), { recursive: true });
  mkdirSync(path.join(dir, 'contracts'), { recursive: true });
  mkdirSync(path.join(dir, 'ccrs'), { recursive: true });
  mkdirSync(path.join(dir, 'spec-candidates'), { recursive: true });
  return writeMissionState(workspace, mission);
}

export interface MissionListResult {
  missions: MissionState[];
  diagnostics: Diagnostic[];
}

/** All missions, newest first. Unreadable records become diagnostics. */
export function listMissions(workspace: WorkspaceInfo): MissionListResult {
  const root = missionsRootDir(workspace);
  if (!existsSync(root)) return { missions: [], diagnostics: [] };
  const missions: MissionState[] = [];
  const diagnostics: Diagnostic[] = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (!ID_PATTERN.test(entry.name)) continue;
    const read = readMissionState(workspace, entry.name);
    if (read.kind === 'ok') {
      missions.push(read.mission);
      continue;
    }
    if (read.kind === 'missing') continue;
    diagnostics.push({
      severity: 'warning',
      code:
        read.kind === 'unsupported-version'
          ? 'MISSION_STATE_UNSUPPORTED_VERSION'
          : 'MISSION_STATE_UNREADABLE',
      message:
        read.kind === 'unsupported-version'
          ? `Mission ${entry.name} uses state schema ${read.version}; ignoring it.`
          : `Mission ${entry.name} has unreadable state; ignoring it.`,
      file: read.file,
    });
  }
  missions.sort(
    (a, b) =>
      b.createdAt.localeCompare(a.createdAt, 'en') || b.missionId.localeCompare(a.missionId, 'en'),
  );
  return { missions, diagnostics };
}

/** The mission that synthesized `specName`, when exactly one exists. */
export function findMissionForSpec(
  workspace: WorkspaceInfo,
  specName: string,
): MissionState | undefined {
  const { missions } = listMissions(workspace);
  const matches = missions.filter((mission) => mission.specName === specName);
  // Two missions claiming one spec would be ambiguous provenance; refuse to
  // guess and treat the spec as not mission-driven.
  return matches.length === 1 ? matches[0] : undefined;
}

// ---------------------------------------------------------------------------
// Append-only jsonl histories with fold-by-id current views
// ---------------------------------------------------------------------------

function appendJsonl(
  workspace: WorkspaceInfo,
  missionId: string,
  fileName: string,
  record: Record<string, unknown>,
  limits: { maxRecordBytes: number },
): void {
  const line = `${JSON.stringify(record)}\n`;
  if (Buffer.byteLength(line, 'utf8') > limits.maxRecordBytes) {
    throw new MissionError(
      'SBM006',
      `A ${fileName} record is larger than the ${limits.maxRecordBytes}-byte limit and was not recorded.`,
      { remediation: ['Mission records are bounded summaries; keep them short.'] },
    );
  }
  const file = artifactPath(workspace, missionId, fileName);
  mkdirSync(path.dirname(file), { recursive: true });
  appendFileSync(file, line, 'utf8');
}

function readJsonl(workspace: WorkspaceInfo, missionId: string, fileName: string): unknown[] {
  const file = artifactPath(workspace, missionId, fileName);
  if (!existsSync(file)) return [];
  let raw: string;
  try {
    raw = readFileSync(file, 'utf8');
  } catch {
    return [];
  }
  const records: unknown[] = [];
  for (const line of raw.split('\n')) {
    if (line.trim().length === 0) continue;
    try {
      records.push(JSON.parse(line));
    } catch {
      // A partially written final line (crash during append) is skipped; the
      // rest of the history stays readable.
    }
  }
  return records;
}

/** Fold an append-only history to its current view: last record per id wins. */
function foldById<T>(records: T[], idOf: (record: T) => string): T[] {
  const byId = new Map<string, T>();
  for (const record of records) byId.set(idOf(record), record);
  return [...byId.values()];
}

const RECORD_LIMITS = { maxRecordBytes: 32_768 } as const;

// --- Turns ---

export function appendTurn(workspace: WorkspaceInfo, missionId: string, turn: ConversationTurn): void {
  appendJsonl(workspace, missionId, 'conversation.jsonl', conversationTurnSchema.parse(turn), RECORD_LIMITS);
}

export interface TurnPage {
  turns: ConversationTurn[];
  total: number;
  truncated: boolean;
}

/** Read a bounded page of turns, newest last. Never unbounded. */
export function readTurns(
  workspace: WorkspaceInfo,
  missionId: string,
  options: { limit?: number; offset?: number } = {},
): TurnPage {
  const parsed: ConversationTurn[] = [];
  for (const record of readJsonl(workspace, missionId, 'conversation.jsonl')) {
    const result = conversationTurnSchema.safeParse(record);
    if (result.success) parsed.push(result.data);
  }
  const limit = Math.max(1, Math.min(options.limit ?? 50, 500));
  const offset = Math.max(0, options.offset ?? 0);
  const window = parsed.slice(Math.max(0, parsed.length - offset - limit), parsed.length - offset);
  return { turns: window, total: parsed.length, truncated: parsed.length > window.length };
}

export function findTurn(
  workspace: WorkspaceInfo,
  missionId: string,
  turnId: string,
): ConversationTurn | undefined {
  for (const record of readJsonl(workspace, missionId, 'conversation.jsonl')) {
    const result = conversationTurnSchema.safeParse(record);
    if (result.success && result.data.turnId === turnId) return result.data;
  }
  return undefined;
}

// --- Facts ---

export function appendFact(workspace: WorkspaceInfo, missionId: string, fact: MissionFact): void {
  appendJsonl(workspace, missionId, 'facts.jsonl', missionFactSchema.parse(fact), RECORD_LIMITS);
}

/** Current facts: the append-only history folded by id. */
export function readFacts(workspace: WorkspaceInfo, missionId: string): MissionFact[] {
  const parsed: MissionFact[] = [];
  for (const record of readJsonl(workspace, missionId, 'facts.jsonl')) {
    const result = missionFactSchema.safeParse(record);
    if (result.success) parsed.push(result.data);
  }
  return foldById(parsed, (fact) => fact.factId);
}

// --- Questions ---

export function appendQuestion(
  workspace: WorkspaceInfo,
  missionId: string,
  question: DiscoveryQuestion,
): void {
  appendJsonl(workspace, missionId, 'questions.jsonl', discoveryQuestionSchema.parse(question), RECORD_LIMITS);
}

export function readQuestions(workspace: WorkspaceInfo, missionId: string): DiscoveryQuestion[] {
  const parsed: DiscoveryQuestion[] = [];
  for (const record of readJsonl(workspace, missionId, 'questions.jsonl')) {
    const result = discoveryQuestionSchema.safeParse(record);
    if (result.success) parsed.push(result.data);
  }
  return foldById(parsed, (question) => question.questionId);
}

// --- Decisions ---

export function appendDecision(
  workspace: WorkspaceInfo,
  missionId: string,
  decision: DiscoveryDecision,
): void {
  appendJsonl(workspace, missionId, 'decisions.jsonl', discoveryDecisionSchema.parse(decision), RECORD_LIMITS);
}

export function readDecisions(workspace: WorkspaceInfo, missionId: string): DiscoveryDecision[] {
  const parsed: DiscoveryDecision[] = [];
  for (const record of readJsonl(workspace, missionId, 'decisions.jsonl')) {
    const result = discoveryDecisionSchema.safeParse(record);
    if (result.success) parsed.push(result.data);
  }
  return foldById(parsed, (decision) => decision.decisionId);
}

// ---------------------------------------------------------------------------
// Coverage / constitution (atomic snapshots)
// ---------------------------------------------------------------------------

export function writeCoverage(
  workspace: WorkspaceInfo,
  missionId: string,
  coverage: MissionCoverage,
): MissionCoverage {
  const validated = missionCoverageSchema.parse(coverage);
  writeFileAtomic(
    artifactPath(workspace, missionId, 'coverage.json'),
    `${JSON.stringify(validated, null, 2)}\n`,
  );
  return validated;
}

export function readCoverage(
  workspace: WorkspaceInfo,
  missionId: string,
): MissionCoverage | undefined {
  const file = artifactPath(workspace, missionId, 'coverage.json');
  if (!existsSync(file)) return undefined;
  try {
    const result = missionCoverageSchema.safeParse(JSON.parse(readFileSync(file, 'utf8')));
    return result.success ? result.data : undefined;
  } catch {
    return undefined;
  }
}

export function writeConstitution(
  workspace: WorkspaceInfo,
  missionId: string,
  constitution: MissionConstitution,
): MissionConstitution {
  const validated = missionConstitutionSchema.parse(constitution);
  writeFileAtomic(
    artifactPath(workspace, missionId, 'constitution.json'),
    `${JSON.stringify(validated, null, 2)}\n`,
  );
  return validated;
}

export function readConstitution(
  workspace: WorkspaceInfo,
  missionId: string,
): MissionConstitution | undefined {
  const file = artifactPath(workspace, missionId, 'constitution.json');
  if (!existsSync(file)) return undefined;
  try {
    const result = missionConstitutionSchema.safeParse(JSON.parse(readFileSync(file, 'utf8')));
    return result.success ? result.data : undefined;
  } catch {
    return undefined;
  }
}

// ---------------------------------------------------------------------------
// ADRs (immutable files)
// ---------------------------------------------------------------------------

export function storeAdr(workspace: WorkspaceInfo, missionId: string, adr: MissionAdr): string {
  const validated = missionAdrSchema.parse(adr);
  if (!ID_PATTERN.test(validated.adrId)) {
    throw new MissionError('SBM005', `Invalid ADR id "${validated.adrId}".`);
  }
  const file = artifactPath(workspace, missionId, 'adrs', `${validated.adrId}.json`);
  if (existsSync(file)) {
    throw new MissionError(
      'SBM010',
      `ADR ${validated.adrId} already exists; ADR files are immutable. Record a superseding ADR instead.`,
    );
  }
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return file;
}

/**
 * All ADRs with DERIVED effective status: an ADR is superseded exactly when
 * a later ADR names it in `supersedes`. Files are never rewritten.
 */
export function readAdrs(workspace: WorkspaceInfo, missionId: string): MissionAdr[] {
  const dir = artifactPath(workspace, missionId, 'adrs');
  if (!existsSync(dir)) return [];
  const adrs: MissionAdr[] = [];
  for (const name of readdirSync(dir).sort()) {
    if (!name.endsWith('.json')) continue;
    try {
      const result = missionAdrSchema.safeParse(
        JSON.parse(readFileSync(path.join(dir, name), 'utf8')),
      );
      if (result.success) adrs.push(result.data);
    } catch {
      // An unreadable ADR is skipped from views; the file is preserved.
    }
  }
  const superseded = new Set(
    adrs.map((adr) => adr.supersedes).filter((id): id is string => id !== undefined),
  );
  return adrs.map((adr) =>
    superseded.has(adr.adrId) ? { ...adr, status: 'superseded' as const } : adr,
  );
}

export function readAdr(
  workspace: WorkspaceInfo,
  missionId: string,
  adrId: string,
): MissionAdr | undefined {
  return readAdrs(workspace, missionId).find((adr) => adr.adrId === adrId);
}

// ---------------------------------------------------------------------------
// Contract registry (immutable per-revision files)
// ---------------------------------------------------------------------------

function contractFileName(contractId: string, revision: number): string {
  return `${contractId}-r${String(revision).padStart(3, '0')}.json`;
}

export function storeContractRevision(
  workspace: WorkspaceInfo,
  missionId: string,
  contract: ProductContract,
): string {
  const validated = productContractSchema.parse(contract);
  if (!ID_PATTERN.test(validated.contractId)) {
    throw new MissionError('SBM005', `Invalid contract id "${validated.contractId}".`);
  }
  const file = artifactPath(
    workspace,
    missionId,
    'contracts',
    contractFileName(validated.contractId, validated.revision),
  );
  if (existsSync(file)) {
    throw new MissionError(
      'SBM010',
      `Contract ${validated.contractId} revision ${validated.revision} already exists; revisions are immutable.`,
    );
  }
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return file;
}

/** Every stored contract revision, ascending by (contractId, revision). */
export function readContractRevisions(
  workspace: WorkspaceInfo,
  missionId: string,
): ProductContract[] {
  const dir = artifactPath(workspace, missionId, 'contracts');
  if (!existsSync(dir)) return [];
  const contracts: ProductContract[] = [];
  for (const name of readdirSync(dir).sort()) {
    if (!name.endsWith('.json')) continue;
    try {
      const result = productContractSchema.safeParse(
        JSON.parse(readFileSync(path.join(dir, name), 'utf8')),
      );
      if (result.success) contracts.push(result.data);
    } catch {
      // Unreadable revisions are skipped from views and preserved on disk.
    }
  }
  contracts.sort(
    (a, b) => a.contractId.localeCompare(b.contractId, 'en') || a.revision - b.revision,
  );
  return contracts;
}

/**
 * The current registry view: the highest revision per contract id, with
 * superseded revisions' status derived.
 */
export function readContractRegistry(
  workspace: WorkspaceInfo,
  missionId: string,
): ProductContract[] {
  const byId = new Map<string, ProductContract>();
  for (const revision of readContractRevisions(workspace, missionId)) {
    const current = byId.get(revision.contractId);
    if (current === undefined || revision.revision > current.revision) {
      byId.set(revision.contractId, revision);
    }
  }
  return [...byId.values()].sort((a, b) => a.contractId.localeCompare(b.contractId, 'en'));
}

export function readContract(
  workspace: WorkspaceInfo,
  missionId: string,
  contractId: string,
  revision?: number,
): ProductContract | undefined {
  if (revision !== undefined) {
    return readContractRevisions(workspace, missionId).find(
      (contract) => contract.contractId === contractId && contract.revision === revision,
    );
  }
  return readContractRegistry(workspace, missionId).find(
    (contract) => contract.contractId === contractId,
  );
}

// ---------------------------------------------------------------------------
// Contract change requests
// ---------------------------------------------------------------------------

export function writeCcr(
  workspace: WorkspaceInfo,
  missionId: string,
  ccr: ContractChangeRequest,
): ContractChangeRequest {
  const validated = contractChangeRequestSchema.parse(ccr);
  if (!ID_PATTERN.test(validated.ccrId)) {
    throw new MissionError('SBM013', `Invalid change request id "${validated.ccrId}".`);
  }
  const file = artifactPath(workspace, missionId, 'ccrs', `${validated.ccrId}.json`);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return validated;
}

export function readCcrs(workspace: WorkspaceInfo, missionId: string): ContractChangeRequest[] {
  const dir = artifactPath(workspace, missionId, 'ccrs');
  if (!existsSync(dir)) return [];
  const ccrs: ContractChangeRequest[] = [];
  for (const name of readdirSync(dir).sort()) {
    if (!name.endsWith('.json')) continue;
    try {
      const result = contractChangeRequestSchema.safeParse(
        JSON.parse(readFileSync(path.join(dir, name), 'utf8')),
      );
      if (result.success) ccrs.push(result.data);
    } catch {
      // Preserved on disk, skipped from views.
    }
  }
  return ccrs;
}

export function readCcr(
  workspace: WorkspaceInfo,
  missionId: string,
  ccrId: string,
): ContractChangeRequest | undefined {
  return readCcrs(workspace, missionId).find((ccr) => ccr.ccrId === ccrId);
}

// ---------------------------------------------------------------------------
// Spec candidates
// ---------------------------------------------------------------------------

/** Store one synthesized stage candidate for audit before spec creation. */
export function writeSpecCandidate(
  workspace: WorkspaceInfo,
  missionId: string,
  fileName: 'requirements.md' | 'design.md' | 'tasks.md' | 'provenance.json',
  content: string,
): string {
  const file = artifactPath(workspace, missionId, 'spec-candidates', fileName);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, content);
  return file;
}

export function readSpecCandidate(
  workspace: WorkspaceInfo,
  missionId: string,
  fileName: 'requirements.md' | 'design.md' | 'tasks.md' | 'provenance.json',
): string | undefined {
  const file = artifactPath(workspace, missionId, 'spec-candidates', fileName);
  if (!existsSync(file)) return undefined;
  try {
    return readFileSync(file, 'utf8');
  } catch {
    return undefined;
  }
}

// ---------------------------------------------------------------------------
// Events and checkpoints
// ---------------------------------------------------------------------------

export interface MissionEvent extends Record<string, unknown> {
  at: string;
  type: MissionEventType;
}

export function appendMissionEvent(
  workspace: WorkspaceInfo,
  missionId: string,
  event: MissionEvent,
): void {
  appendJsonl(workspace, missionId, 'events.jsonl', event, { maxRecordBytes: 8_192 });
}

export interface MissionEventPage {
  events: MissionEvent[];
  total: number;
  truncated: boolean;
}

export function readMissionEvents(
  workspace: WorkspaceInfo,
  missionId: string,
  options: { limit?: number; offset?: number } = {},
): MissionEventPage {
  const parsed = readJsonl(workspace, missionId, 'events.jsonl').filter(
    (record): record is MissionEvent => record !== null && typeof record === 'object',
  );
  const limit = Math.max(1, Math.min(options.limit ?? 50, 500));
  const offset = Math.max(0, options.offset ?? 0);
  const window = parsed.slice(Math.max(0, parsed.length - offset - limit), parsed.length - offset);
  return { events: window, total: parsed.length, truncated: parsed.length > window.length };
}

export function countMissionEvents(workspace: WorkspaceInfo, missionId: string): number {
  return readJsonl(workspace, missionId, 'events.jsonl').length;
}

export function writeMissionCheckpoint(
  workspace: WorkspaceInfo,
  missionId: string,
  checkpoint: MissionCheckpoint,
): string {
  const validated = missionCheckpointSchema.parse(checkpoint);
  const file = artifactPath(workspace, missionId, 'checkpoint.json');
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return file;
}

export function readMissionCheckpoint(
  workspace: WorkspaceInfo,
  missionId: string,
): MissionCheckpoint | undefined {
  const file = artifactPath(workspace, missionId, 'checkpoint.json');
  if (!existsSync(file)) return undefined;
  try {
    const result = missionCheckpointSchema.safeParse(JSON.parse(readFileSync(file, 'utf8')));
    return result.success ? result.data : undefined;
  } catch {
    return undefined;
  }
}
