import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import type { StageName, WorkspaceInfo } from '@specbridge/core';
import { sha256Hex } from '@specbridge/core';
import { analyzeSpec, requireSpec } from '@specbridge/compat-kiro';
import { SYNTHESIS_TEMPLATE_STATEMENTS } from '@specbridge/mission';
import type { ApprovalResult } from '@specbridge/workflow';
import { approveStage } from '@specbridge/workflow';
import { IntakeError } from './errors.js';
import type { IntakeApproval, ProjectionDivergence, ProjectionEquivalence } from './state.js';
import { INTAKE_LIMITS } from './state.js';
import { clip, containment, jaccard, tokenSet } from './text.js';

/**
 * Derived approval.
 *
 * The legacy workflow is right for the legacy workflow: a human writes
 * requirements, a human reads them, a human approves them. Nothing about
 * that changes.
 *
 * The single-approval path is a different situation and deserves a different
 * answer. There, the human approved the CANONICAL PRODUCT TRUTH — the goal,
 * the non-goals, the contracts, the acceptance criteria, the answers to
 * every product question — and `requirements.md`, `design.md`, and
 * `tasks.md` are deterministic projections of exactly that. Asking the same
 * person to approve the same truth three more times because the compiler
 * emitted three files is ceremony, not governance.
 *
 * So the authority DERIVES. And the derivation is only sound under one
 * condition, which this file exists to prove rather than assume:
 *
 *   the projection must contain no semantic authority the human did not
 *   approve.
 *
 * If it does, the derived approval FAILS. Not warns — fails. An artifact
 * carrying an unapproved promise is exactly the artifact a human needs to
 * read, and degrading that to a warning would turn the whole mechanism into
 * a way of laundering unapproved requirements into an approved spec.
 *
 * What is deliberately NOT done here: forging a manual approval receipt. A
 * derived stage records `approvalMode: DERIVED_FROM_INTENT_APPROVAL` plus
 * the approval id and the authority digest, so an audit can always answer
 * "which human decision authorized this artifact?" — and can tell that the
 * answer is a product approval rather than a document review.
 */

// ---------------------------------------------------------------------------
// Extracting semantic authority from a compiled artifact
// ---------------------------------------------------------------------------

/**
 * Lines that assert something the product must do.
 *
 * The compiled documents are Kiro Markdown, so the normative lines have
 * recognisable shapes: EARS acceptance criteria, requirement statements,
 * invariant bullets, and objective acceptance criteria. Prose headings,
 * tables of contents, and provenance footers are structure, not authority.
 */
const NORMATIVE_LINE_PATTERNS: readonly RegExp[] = Object.freeze([
  /\bSHALL\b/,
  /\bMUST\b/,
  /^\s*[-*]\s+(WHEN|IF|WHILE|WHERE)\b/i,
  /^\s*\*\*(Requirement|Invariant|Acceptance)\b/i,
  /^\s*[-*]\s+\*\*(Acceptance|Invariant|Criterion)\b/i,
]);

/**
 * The compiler's own fixed statements, normalized for comparison.
 *
 * Imported from the compiler rather than restated, so the two can never
 * drift. These lines are emitted identically for every mission and carry no
 * mission-specific authority — "respect the Architecture Constitution" is
 * something SpecBridge guarantees about any synthesized spec, not a promise
 * this product made. Matching is EXACT, which is what stops the exemption
 * from being a loophole: no mission content can equal one of them by
 * accident, and a template that grew a real promise would have to add it
 * to a list a reviewer reads.
 */
const TEMPLATE_STATEMENTS: ReadonlySet<string> = new Set(
  SYNTHESIS_TEMPLATE_STATEMENTS.map((statement) => normalizeStatement(statement)),
);

function normalizeStatement(value: string): string {
  return value
    .trim()
    .replace(/^[-*]\s+/, '')
    .replace(/\*\*/g, '')
    .replace(/\s+/g, ' ')
    .toLowerCase();
}

/** Lines that are structure rather than authority, whatever they contain. */
const STRUCTURAL_LINE_PATTERNS: readonly RegExp[] = Object.freeze([
  /^\s*#{1,6}\s/,
  /^\s*\|/,
  /^\s*```/,
  /^\s*>/,
  /^\s*<!--/,
  /^\s*_?Generated by SpecBridge/i,
  /^\s*\*?Provenance:/i,
]);

export interface ExtractedStatement {
  stage: StageName;
  line: number;
  statement: string;
}

/** Every normative statement in one compiled document. */
export function extractNormativeStatements(
  stage: StageName,
  content: string,
): ExtractedStatement[] {
  const out: ExtractedStatement[] = [];
  const lines = content.split('\n');
  for (const [index, raw] of lines.entries()) {
    const line = raw.trim();
    if (line.length === 0) continue;
    if (STRUCTURAL_LINE_PATTERNS.some((pattern) => pattern.test(raw))) continue;
    if (!NORMATIVE_LINE_PATTERNS.some((pattern) => pattern.test(line))) continue;
    if (TEMPLATE_STATEMENTS.has(normalizeStatement(line))) continue;
    out.push({
      stage,
      line: index + 1,
      statement: clip(line.replace(/^[-*]\s+/, '').replace(/\*\*/g, ''), 1_000),
    });
    if (out.length >= INTAKE_LIMITS.maxItems) break;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Equivalence
// ---------------------------------------------------------------------------

/**
 * How much of a projected statement's content must appear in some approved
 * element before it counts as traced.
 *
 * Lower than the delta matcher's threshold, and that is correct: the
 * compiler REWRITES approved truth into EARS form, so "the system SHALL
 * reject an invalid boarding pass before any side effect" legitimately
 * contains connective vocabulary the approved decision did not. What must
 * carry over is the content, and containment measures exactly that.
 */
const TRACE_CONTAINMENT = 0.5;

/** Two statements are the same statement above this symmetric overlap. */
const TRACE_JACCARD = 0.45;

export interface EquivalenceRequest {
  workspace: WorkspaceInfo;
  approval: IntakeApproval;
  specName: string;
  checkedAt: string;
  /** The approved canonical elements, as text. Built by `approvedElements`. */
  approvedElements: readonly { id: string; text: string }[];
  /** Stages to check. Defaults to the three the compiler emits. */
  stages?: readonly StageName[] | undefined;
  /** Recomputed digest of the canonical truth, for the drift check. */
  currentAuthorityDigest: string;
}

/**
 * Prove — or refuse — that the compiled spec projects exactly the approved
 * truth.
 *
 * Three checks, and the order matters. Digest drift is checked FIRST: if the
 * canonical truth moved after the human approved it, nothing downstream is
 * meaningful, and a per-statement report would be a distraction from the one
 * fact that matters.
 */
export function checkProjectionEquivalence(request: EquivalenceRequest): ProjectionEquivalence {
  const divergences: ProjectionDivergence[] = [];
  const artifactHashes: Record<string, string> = {};

  if (request.currentAuthorityDigest !== request.approval.authorityDigest) {
    divergences.push({
      kind: 'AUTHORITY_DIGEST_MISMATCH',
      detail:
        `The canonical product truth changed after approval ${request.approval.approvalId} ` +
        `(approved ${request.approval.authorityDigest}, current ` +
        `${request.currentAuthorityDigest}). Derived authority cannot span a change the ` +
        'human did not see.',
    });
    return {
      schemaVersion: '1.0.0',
      intakeId: request.approval.intakeId,
      approvalId: request.approval.approvalId,
      specName: request.specName,
      checkedAt: request.checkedAt,
      equivalent: false,
      checkedStatements: 0,
      tracedStatements: 0,
      divergences,
      artifactHashes,
    };
  }

  const stages: readonly StageName[] = request.stages ?? ['requirements', 'design', 'tasks'];
  const folder = requireSpec(request.workspace, request.specName);
  void analyzeSpec(request.workspace, folder);

  const approvedTokens = request.approvedElements.map((element) => ({
    id: element.id,
    tokens: tokenSet(element.text),
  }));

  let checked = 0;
  let traced = 0;

  for (const stage of stages) {
    const file = path.join(folder.dir, `${stage}.md`);
    if (!existsSync(file)) {
      divergences.push({
        kind: 'UNRELATED_ARTIFACT',
        stage,
        detail: `The compiled spec has no ${stage}.md, so nothing can be derived for it.`,
      });
      continue;
    }
    const content = readFileSync(file, 'utf8');
    artifactHashes[stage] = sha256Hex(content);

    for (const statement of extractNormativeStatements(stage, content)) {
      checked += 1;
      const tokens = tokenSet(statement.statement);
      if (tokens.size === 0) {
        traced += 1;
        continue;
      }
      const match = approvedTokens.find(
        (element) =>
          containment(tokens, element.tokens) >= TRACE_CONTAINMENT ||
          jaccard(tokens, element.tokens) >= TRACE_JACCARD,
      );
      if (match === undefined) {
        divergences.push({
          kind: 'UNAPPROVED_AUTHORITY',
          stage,
          detail:
            `${stage}.md line ${statement.line} states authority that traces to nothing the ` +
            'human approved.',
          statement: clip(statement.statement, 600),
        });
        continue;
      }
      traced += 1;
    }
  }

  return {
    schemaVersion: '1.0.0',
    intakeId: request.approval.intakeId,
    approvalId: request.approval.approvalId,
    specName: request.specName,
    checkedAt: request.checkedAt,
    equivalent: divergences.length === 0,
    checkedStatements: checked,
    tracedStatements: traced,
    divergences: divergences.slice(0, INTAKE_LIMITS.maxItems),
    artifactHashes,
  };
}

/**
 * The approved canonical elements, as searchable text.
 *
 * Everything the human explicitly authorized and nothing else: the goal, the
 * non-goals, the acceptance criteria, the recorded answers, and the contract
 * requirements and invariants the approval names. A projection statement
 * that traces to none of these is, by construction, authority nobody
 * approved.
 */
export function approvedElements(
  approval: IntakeApproval,
  contracts: readonly {
    contractId: string;
    requirements: readonly { requirementId: string; statement: string }[];
    invariants: readonly { invariantId: string; statement: string }[];
    title: string;
    summary: string;
  }[],
  decisions: readonly { decisionId: string; decision: string }[],
): { id: string; text: string }[] {
  const out: { id: string; text: string }[] = [{ id: 'GOAL', text: approval.goal }];
  approval.nonGoals.forEach((statement, index) =>
    out.push({ id: `NON-GOAL-${index + 1}`, text: statement }),
  );
  approval.acceptanceCriteria.forEach((statement, index) =>
    out.push({ id: `AC-${index + 1}`, text: statement }),
  );
  for (const resolved of approval.resolvedQuestions) {
    out.push({ id: `ANSWER-${resolved.questionId}`, text: `${resolved.question} ${resolved.answer}` });
  }
  for (const contract of contracts) {
    out.push({
      id: contract.contractId,
      text: `${contract.title} ${contract.summary}`,
    });
    for (const requirement of contract.requirements) {
      out.push({
        id: `${contract.contractId}/${requirement.requirementId}`,
        text: requirement.statement,
      });
    }
    for (const invariant of contract.invariants) {
      out.push({
        id: `${contract.contractId}/${invariant.invariantId}`,
        text: invariant.statement,
      });
    }
  }
  const approvedDecisions = new Set(approval.decisionIds);
  for (const decision of decisions) {
    if (!approvedDecisions.has(decision.decisionId)) continue;
    out.push({ id: decision.decisionId, text: decision.decision });
  }
  return out;
}

// ---------------------------------------------------------------------------
// Recording the derived approvals
// ---------------------------------------------------------------------------

export interface DeriveApprovalsRequest {
  workspace: WorkspaceInfo;
  approval: IntakeApproval;
  specName: string;
  equivalence: ProjectionEquivalence;
  stages?: readonly StageName[] | undefined;
  clock: () => Date;
}

export interface DeriveApprovalsResult {
  approved: StageName[];
  results: ApprovalResult[];
}

/**
 * Stamp each projected stage with derived authority.
 *
 * Refuses outright when the equivalence check did not pass. The ordinary
 * approval gates still run underneath — prerequisites, deterministic
 * analysis, the byte-exact hash — because a derived approval is an approval
 * with a different PROVENANCE, not an approval with fewer checks.
 */
export function recordDerivedApprovals(
  request: DeriveApprovalsRequest,
): DeriveApprovalsResult {
  if (!request.equivalence.equivalent) {
    throw new IntakeError(
      'SBI013',
      `The compiled spec "${request.specName}" contains authority the human approval does not ` +
        `cover (${request.equivalence.divergences.length} divergence(s)).`,
      {
        remediation: [
          'Review the generated documents and approve them manually with ' +
            '`specbridge spec approve <name> --stage <stage>`,',
          'or reopen discovery so the divergent authority becomes approved product truth.',
          ...request.equivalence.divergences
            .slice(0, 5)
            .map((divergence) => `${divergence.kind}: ${divergence.detail}`),
        ],
        details: {
          specName: request.specName,
          divergences: request.equivalence.divergences.length,
        },
      },
    );
  }

  const stages: readonly StageName[] = request.stages ?? ['requirements', 'design', 'tasks'];
  const approved: StageName[] = [];
  const results: ApprovalResult[] = [];

  for (const stage of stages) {
    const folder = requireSpec(request.workspace, request.specName);
    const spec = analyzeSpec(request.workspace, folder);
    const result = approveStage(
      request.workspace,
      spec,
      {
        stage,
        derivedFrom: {
          approvalId: request.approval.approvalId,
          authorityDigest: request.approval.authorityDigest,
        },
      },
      { clock: request.clock },
    );
    results.push(result);
    if (!result.ok) {
      throw new IntakeError(
        'SBI014',
        `Derived approval of ${stage} failed: ${result.message}`,
        {
          remediation: [
            `Inspect the generated document with \`specbridge spec analyze ${request.specName} --stage ${stage}\`.`,
          ],
          details: { stage, reason: result.reason },
        },
      );
    }
    approved.push(stage);
  }

  return { approved, results };
}

/**
 * Which human decision authorized one stage of one spec.
 *
 * The audit answer, computed from durable state. Exported because the
 * question has to be answerable from outside this package — a reviewer, a
 * report, and the CLI all ask it, and each of them re-deriving the logic
 * would be three chances to get it wrong.
 */
export function describeStageAuthority(stage: {
  status: string;
  approvedAt: string | null;
  approvalMode?: string | undefined;
  sourceApprovalId?: string | undefined;
  authorityDigest?: string | undefined;
}): string {
  if (stage.status !== 'approved') return 'not approved';
  if (stage.approvalMode === 'DERIVED_FROM_INTENT_APPROVAL') {
    return (
      `derived from human approval ${stage.sourceApprovalId ?? '(unnamed)'} ` +
      `(authority ${stage.authorityDigest ?? '(unnamed)'})`
    );
  }
  return `approved directly by a human at ${stage.approvedAt ?? 'an unrecorded time'}`;
}
