import {
  appendFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
} from 'node:fs';
import path from 'node:path';
import type { WorkspaceInfo } from '@specbridge/core';
import { assertInsideWorkspace, writeFileAtomic } from '@specbridge/core';
import { IntakeError } from './errors.js';
import type {
  BuildLifecycle,
  DeltaAuthorityAnalysis,
  IntakeApproval,
  ProductBaseline,
  ProductQuestion,
  ProjectionEquivalence,
  QuestionRefusal,
  RepositoryGrounding,
  SpecIntakeState,
  SpecSource,
} from './state.js';
import {
  PRODUCT_BASELINE_SCHEMA_VERSION,
  buildLifecycleSchema,
  deltaAuthorityAnalysisSchema,
  intakeApprovalSchema,
  productBaselineSchema,
  productQuestionSchema,
  projectionEquivalenceSchema,
  questionRefusalSchema,
  repositoryGroundingSchema,
  specIntakeStateSchema,
  specSourceSchema,
} from './state.js';

/**
 * Spec-intake persistence:
 *
 *   .specbridge/intake/
 *     baseline.json                      product baseline + feature lineage
 *     <intakeId>/
 *       intake.json                      the intake state
 *       source/<sha256>.md               the submitted specification, verbatim
 *       source.json                      provenance + deterministic chunk index
 *       grounding.json                   repository-grounded discovery report
 *       delta.json                       delta authority analysis
 *       questions.jsonl                  admitted product questions (fold by id)
 *       refusals.jsonl                   candidate questions declined, and why
 *       approval.json                    THE human authorization (immutable)
 *       projection.json                  projection equivalence verdict
 *       lifecycle.json                   the seal-and-build step ledger
 *       events.jsonl                     append-only intake history
 *
 * Same guarantees as every other SpecBridge state family: every path passes
 * `assertInsideWorkspace`, every write is atomic, and a corrupt record is
 * skipped by listings and left on disk for diagnosis rather than rewritten.
 *
 * Two rules specific to this family.
 *
 * THE SUBMITTED SPECIFICATION IS NEVER REWRITTEN. It is written once, under
 * a content-addressed name, and re-ingesting identical bytes is a no-op
 * rather than an overwrite. The original text is product evidence, and
 * evidence that can be edited in place is not evidence.
 *
 * THE APPROVAL IS IMMUTABLE. `writeApproval` refuses an existing path
 * outright. An authorization that can be edited is not an authorization; the
 * only field the lifecycle later adds is the seal id, and it does that
 * through `bindApprovalSeal`, which refuses to change one already set.
 */

const ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

export const INTAKE_DIR_NAME = 'intake';

export function assertIntakeId(id: string): string {
  if (!ID_PATTERN.test(id)) {
    throw new IntakeError('SBI005', `Invalid spec intake id "${id}".`, {
      remediation: ['Ids are generated by SpecBridge; pass one returned by an intake operation.'],
      details: { id },
    });
  }
  return id;
}

export function intakeRootDir(workspace: WorkspaceInfo): string {
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(workspace.rootDir, '.specbridge', INTAKE_DIR_NAME),
  );
}

export function intakeDir(workspace: WorkspaceInfo, intakeId: string): string {
  assertIntakeId(intakeId);
  return assertInsideWorkspace(workspace.rootDir, path.join(intakeRootDir(workspace), intakeId));
}

function intakePath(workspace: WorkspaceInfo, intakeId: string, ...segments: string[]): string {
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(intakeDir(workspace, intakeId), ...segments),
  );
}

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

function writeJson(file: string, value: unknown): void {
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(value, null, 2)}\n`);
}

function readJson<T>(file: string, parse: (raw: unknown) => T): T | undefined {
  if (!existsSync(file)) return undefined;
  try {
    return parse(JSON.parse(readFileSync(file, 'utf8')));
  } catch {
    return undefined;
  }
}

function appendJsonl(file: string, value: Record<string, unknown>): void {
  mkdirSync(path.dirname(file), { recursive: true });
  appendFileSync(file, `${JSON.stringify(value)}\n`, 'utf8');
}

/**
 * Read a JSONL log and fold by id, last record winning.
 *
 * The same append-only-with-fold shape the mission store uses for facts,
 * questions, and decisions: history is never rewritten, and the current view
 * is derived.
 */
function readFolded<T>(file: string, key: keyof T & string, parse: (raw: unknown) => T): T[] {
  if (!existsSync(file)) return [];
  const folded = new Map<string, T>();
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    if (line.trim().length === 0) continue;
    try {
      const value = parse(JSON.parse(line));
      folded.set(String(value[key]), value);
    } catch {
      // A corrupt line is skipped and left on disk. One bad append must not
      // make the whole discovery record unreadable.
    }
  }
  return [...folded.values()];
}

// ---------------------------------------------------------------------------
// Intake state
// ---------------------------------------------------------------------------

export function intakeStateFile(workspace: WorkspaceInfo, intakeId: string): string {
  return intakePath(workspace, intakeId, 'intake.json');
}

export function readIntakeState(
  workspace: WorkspaceInfo,
  intakeId: string,
): SpecIntakeState | undefined {
  return readJson(intakeStateFile(workspace, intakeId), (raw) => specIntakeStateSchema.parse(raw));
}

export function requireIntakeState(workspace: WorkspaceInfo, intakeId: string): SpecIntakeState {
  const state = readIntakeState(workspace, intakeId);
  if (state === undefined) {
    throw new IntakeError('SBI001', `No spec intake "${intakeId}" exists in this workspace.`, {
      remediation: ['List intakes with `specbridge spec intake`.'],
      details: { intakeId },
    });
  }
  return state;
}

export function writeIntakeState(
  workspace: WorkspaceInfo,
  state: SpecIntakeState,
): SpecIntakeState {
  const validated = specIntakeStateSchema.parse(state);
  writeJson(intakeStateFile(workspace, validated.intakeId), validated);
  return validated;
}

export interface IntakeListResult {
  intakes: SpecIntakeState[];
  /** Directories that exist but could not be read, surfaced not swallowed. */
  diagnostics: { intakeId: string; message: string }[];
}

export function listIntakes(workspace: WorkspaceInfo): IntakeListResult {
  const root = intakeRootDir(workspace);
  if (!existsSync(root)) return { intakes: [], diagnostics: [] };
  const intakes: SpecIntakeState[] = [];
  const diagnostics: IntakeListResult['diagnostics'] = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (!ID_PATTERN.test(entry.name)) continue;
    const file = path.join(root, entry.name, 'intake.json');
    if (!existsSync(file)) continue;
    try {
      intakes.push(specIntakeStateSchema.parse(JSON.parse(readFileSync(file, 'utf8'))));
    } catch (cause) {
      diagnostics.push({
        intakeId: entry.name,
        message: `intake state is unreadable: ${cause instanceof Error ? cause.message : String(cause)}`,
      });
    }
  }
  intakes.sort((a, b) => a.createdAt.localeCompare(b.createdAt));
  return { intakes, diagnostics };
}

/**
 * Resolve a subject to one intake: an intake id, an intake name, a mission
 * id, or a synthesized spec name.
 *
 * Names win over ids only when no id matches, and the NEWEST non-abandoned
 * match wins among equals — a user who runs `spec start airport-demo` twice
 * means the second one.
 */
export function findIntake(
  workspace: WorkspaceInfo,
  subject: string,
): SpecIntakeState | undefined {
  const { intakes } = listIntakes(workspace);
  const byId = intakes.find((intake) => intake.intakeId === subject);
  if (byId !== undefined) return byId;
  const candidates = intakes.filter(
    (intake) =>
      intake.name === subject ||
      intake.missionId === subject ||
      intake.specName === subject,
  );
  const live = candidates.filter((intake) => intake.status !== 'ABANDONED');
  const pool = live.length > 0 ? live : candidates;
  return pool.length === 0 ? undefined : pool[pool.length - 1];
}

// ---------------------------------------------------------------------------
// Source specification
// ---------------------------------------------------------------------------

export function sourceDir(workspace: WorkspaceInfo, intakeId: string): string {
  return intakePath(workspace, intakeId, 'source');
}

export function sourceFile(
  workspace: WorkspaceInfo,
  intakeId: string,
  contentHash: string,
): string {
  if (!/^[0-9a-f]{64}$/.test(contentHash)) {
    throw new IntakeError('SBI007', 'A source specification digest must be a sha256 hex string.');
  }
  return intakePath(workspace, intakeId, 'source', `${contentHash}.md`);
}

/**
 * Store the submitted specification verbatim, content-addressed.
 *
 * Identical bytes are a no-op: the file already on disk IS the evidence, and
 * rewriting it would change its mtime for no reason. Different bytes land
 * beside it under a different name, so a re-submission never destroys what
 * an earlier approval referenced.
 */
export function storeSourceText(
  workspace: WorkspaceInfo,
  intakeId: string,
  contentHash: string,
  content: string,
): string {
  const file = sourceFile(workspace, intakeId, contentHash);
  if (!existsSync(file)) {
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileAtomic(file, content);
  }
  return file;
}

export function readSourceText(
  workspace: WorkspaceInfo,
  intakeId: string,
  contentHash: string,
): string | undefined {
  const file = sourceFile(workspace, intakeId, contentHash);
  if (!existsSync(file)) return undefined;
  try {
    return readFileSync(file, 'utf8');
  } catch {
    return undefined;
  }
}

export function writeSpecSource(workspace: WorkspaceInfo, source: SpecSource): SpecSource {
  const validated = specSourceSchema.parse(source);
  writeJson(intakePath(workspace, validated.intakeId, 'source.json'), validated);
  return validated;
}

export function readSpecSource(
  workspace: WorkspaceInfo,
  intakeId: string,
): SpecSource | undefined {
  return readJson(intakePath(workspace, intakeId, 'source.json'), (raw) =>
    specSourceSchema.parse(raw),
  );
}

export function requireSpecSource(workspace: WorkspaceInfo, intakeId: string): SpecSource {
  const source = readSpecSource(workspace, intakeId);
  if (source === undefined) {
    throw new IntakeError('SBI007', `Spec intake "${intakeId}" has no ingested source document.`, {
      remediation: ['Re-run `specbridge spec start <name> --file <spec-file>`.'],
      details: { intakeId },
    });
  }
  return source;
}

// ---------------------------------------------------------------------------
// Grounding, delta, projection
// ---------------------------------------------------------------------------

export function writeGrounding(
  workspace: WorkspaceInfo,
  grounding: RepositoryGrounding,
): RepositoryGrounding {
  const validated = repositoryGroundingSchema.parse(grounding);
  writeJson(intakePath(workspace, validated.intakeId, 'grounding.json'), validated);
  return validated;
}

export function readGrounding(
  workspace: WorkspaceInfo,
  intakeId: string,
): RepositoryGrounding | undefined {
  return readJson(intakePath(workspace, intakeId, 'grounding.json'), (raw) =>
    repositoryGroundingSchema.parse(raw),
  );
}

export function writeDeltaAnalysis(
  workspace: WorkspaceInfo,
  analysis: DeltaAuthorityAnalysis,
): DeltaAuthorityAnalysis {
  const validated = deltaAuthorityAnalysisSchema.parse(analysis);
  writeJson(intakePath(workspace, validated.intakeId, 'delta.json'), validated);
  return validated;
}

export function readDeltaAnalysis(
  workspace: WorkspaceInfo,
  intakeId: string,
): DeltaAuthorityAnalysis | undefined {
  return readJson(intakePath(workspace, intakeId, 'delta.json'), (raw) =>
    deltaAuthorityAnalysisSchema.parse(raw),
  );
}

export function writeProjectionEquivalence(
  workspace: WorkspaceInfo,
  verdict: ProjectionEquivalence,
): ProjectionEquivalence {
  const validated = projectionEquivalenceSchema.parse(verdict);
  writeJson(intakePath(workspace, validated.intakeId, 'projection.json'), validated);
  return validated;
}

export function readProjectionEquivalence(
  workspace: WorkspaceInfo,
  intakeId: string,
): ProjectionEquivalence | undefined {
  return readJson(intakePath(workspace, intakeId, 'projection.json'), (raw) =>
    projectionEquivalenceSchema.parse(raw),
  );
}

// ---------------------------------------------------------------------------
// Questions and refusals
// ---------------------------------------------------------------------------

export function appendQuestion(
  workspace: WorkspaceInfo,
  intakeId: string,
  question: ProductQuestion,
): void {
  appendJsonl(
    intakePath(workspace, intakeId, 'questions.jsonl'),
    productQuestionSchema.parse(question),
  );
}

export function readQuestions(workspace: WorkspaceInfo, intakeId: string): ProductQuestion[] {
  return readFolded(
    intakePath(workspace, intakeId, 'questions.jsonl'),
    'questionId',
    (raw) => productQuestionSchema.parse(raw),
  ).sort((a, b) => a.questionId.localeCompare(b.questionId));
}

export function appendRefusal(
  workspace: WorkspaceInfo,
  intakeId: string,
  refusal: QuestionRefusal,
): void {
  appendJsonl(
    intakePath(workspace, intakeId, 'refusals.jsonl'),
    questionRefusalSchema.parse(refusal),
  );
}

export function readRefusals(workspace: WorkspaceInfo, intakeId: string): QuestionRefusal[] {
  return readFolded(
    intakePath(workspace, intakeId, 'refusals.jsonl'),
    'refusalId',
    (raw) => questionRefusalSchema.parse(raw),
  ).sort((a, b) => a.refusalId.localeCompare(b.refusalId));
}

// ---------------------------------------------------------------------------
// The approval
// ---------------------------------------------------------------------------

export function approvalFile(workspace: WorkspaceInfo, intakeId: string): string {
  return intakePath(workspace, intakeId, 'approval.json');
}

/**
 * Write the human authorization. Refuses to overwrite an existing one.
 *
 * This is the immutability rule of the whole package: everything downstream
 * — the seal, the derived stage approvals, the launch — cites this record by
 * id and digest, and a record that could be edited afterwards would make
 * every one of those citations meaningless.
 */
export function writeApproval(workspace: WorkspaceInfo, approval: IntakeApproval): IntakeApproval {
  const validated = intakeApprovalSchema.parse(approval);
  const file = approvalFile(workspace, validated.intakeId);
  if (existsSync(file)) {
    throw new IntakeError(
      'SBI017',
      `Spec intake "${validated.intakeId}" is already approved; an approval is immutable.`,
      {
        remediation: [
          'Reopen discovery for a material change, which starts a new approval lifecycle.',
        ],
        details: { intakeId: validated.intakeId },
      },
    );
  }
  writeJson(file, validated);
  return validated;
}

export function readApproval(
  workspace: WorkspaceInfo,
  intakeId: string,
): IntakeApproval | undefined {
  return readJson(approvalFile(workspace, intakeId), (raw) => intakeApprovalSchema.parse(raw));
}

export function requireApproval(workspace: WorkspaceInfo, intakeId: string): IntakeApproval {
  const approval = readApproval(workspace, intakeId);
  if (approval === undefined) {
    throw new IntakeError('SBI011', `Spec intake "${intakeId}" has not been approved.`, {
      remediation: ['Approve it with `specbridge spec approve <name> --build`.'],
      details: { intakeId },
    });
  }
  return approval;
}

/**
 * Record the seal the approval produced.
 *
 * The one mutation an approval record accepts, and it is write-once: binding
 * a different seal to an existing approval would mean two authorizations
 * shared one human decision.
 */
export function bindApprovalSeal(
  workspace: WorkspaceInfo,
  intakeId: string,
  sealId: string,
): IntakeApproval {
  const approval = requireApproval(workspace, intakeId);
  if (approval.sealId !== undefined) {
    if (approval.sealId === sealId) return approval;
    throw new IntakeError(
      'SBI012',
      `Approval ${approval.approvalId} already authorized seal ${approval.sealId}.`,
      { details: { intakeId, existing: approval.sealId, attempted: sealId } },
    );
  }
  const bound = intakeApprovalSchema.parse({ ...approval, sealId });
  writeJson(approvalFile(workspace, intakeId), bound);
  return bound;
}

// ---------------------------------------------------------------------------
// The lifecycle ledger
// ---------------------------------------------------------------------------

export function writeLifecycle(
  workspace: WorkspaceInfo,
  lifecycle: BuildLifecycle,
): BuildLifecycle {
  const validated = buildLifecycleSchema.parse(lifecycle);
  writeJson(intakePath(workspace, validated.intakeId, 'lifecycle.json'), validated);
  return validated;
}

export function readLifecycle(
  workspace: WorkspaceInfo,
  intakeId: string,
): BuildLifecycle | undefined {
  return readJson(intakePath(workspace, intakeId, 'lifecycle.json'), (raw) =>
    buildLifecycleSchema.parse(raw),
  );
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

export interface IntakeEvent extends Record<string, unknown> {
  at: string;
  type: string;
}

export function appendIntakeEvent(
  workspace: WorkspaceInfo,
  intakeId: string,
  event: IntakeEvent,
): void {
  appendJsonl(intakePath(workspace, intakeId, 'events.jsonl'), event);
}

export interface IntakeEventPage {
  events: IntakeEvent[];
  total: number;
  truncated: boolean;
}

export function readIntakeEvents(
  workspace: WorkspaceInfo,
  intakeId: string,
  options: { limit?: number } = {},
): IntakeEventPage {
  const file = intakePath(workspace, intakeId, 'events.jsonl');
  if (!existsSync(file)) return { events: [], total: 0, truncated: false };
  const lines = readFileSync(file, 'utf8')
    .split('\n')
    .filter((line) => line.trim().length > 0);
  const limit = options.limit ?? 200;
  const slice = lines.slice(-limit);
  const events: IntakeEvent[] = [];
  for (const line of slice) {
    try {
      events.push(JSON.parse(line) as IntakeEvent);
    } catch {
      // Skipped, not fatal: the history exists to explain the run.
    }
  }
  return { events, total: lines.length, truncated: lines.length > slice.length };
}

// ---------------------------------------------------------------------------
// Product baseline
// ---------------------------------------------------------------------------

export function baselineFile(workspace: WorkspaceInfo): string {
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(intakeRootDir(workspace), 'baseline.json'),
  );
}

export function readProductBaseline(workspace: WorkspaceInfo): ProductBaseline {
  return (
    readJson(baselineFile(workspace), (raw) => productBaselineSchema.parse(raw)) ?? {
      schemaVersion: PRODUCT_BASELINE_SCHEMA_VERSION,
      updatedAt: '1970-01-01T00:00:00.000Z',
      features: [],
    }
  );
}

export function writeProductBaseline(
  workspace: WorkspaceInfo,
  baseline: ProductBaseline,
): ProductBaseline {
  const validated = productBaselineSchema.parse(baseline);
  writeJson(baselineFile(workspace), validated);
  return validated;
}

/** Bytes the stored source occupies, for reporting on a long specification. */
export function sourceByteLength(
  workspace: WorkspaceInfo,
  intakeId: string,
  contentHash: string,
): number | null {
  try {
    return statSync(sourceFile(workspace, intakeId, contentHash)).size;
  } catch {
    return null;
  }
}
