import { existsSync, mkdirSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import type { WorkspaceInfo } from '@specbridge/core';
import { assertInsideWorkspace, writeFileAtomic } from '@specbridge/core';
import { OrchestrationError } from '../errors.js';
import type {
  DogfoodDefect,
  DogfoodRun,
  FaultInjectionRecord,
  HumanIntervention,
  InvariantAudit,
  ScenarioResult,
} from './state.js';
import {
  dogfoodDefectSchema,
  dogfoodRunSchema,
  faultInjectionRecordSchema,
  humanInterventionSchema,
  invariantAuditSchema,
  scenarioResultSchema,
} from './state.js';

/**
 * Qualification persistence:
 *
 *   .specbridge/qualification/
 *     <runId>/
 *       run.json                     the run record (the one mutable file)
 *       scenarios/<scenarioId>.json  latest result per scenario
 *       faults/<faultId>.json        append-only injection records
 *       audits/<auditId>.json        append-only invariant audits
 *       interventions/<id>.json      append-only human interventions
 *       defects/<defectId>.json      defects, updated as they are resolved
 *       reports/<name>               generated release artifacts
 *
 * Same guarantees as every other SpecBridge state family, for the same
 * reasons: every path passes `assertInsideWorkspace`, every write is atomic,
 * and a corrupt record is skipped by listings and preserved for diagnosis
 * rather than rewritten.
 *
 * Two deliberate design points:
 *
 * Scenario results are keyed by scenario id and REPLACED on re-run rather
 * than appended. A qualification run answers "does this scenario hold now",
 * and a re-run after a fix must be able to turn a FAIL into a PASS — an
 * append-only scenario log would make "failed once, ever" indistinguishable
 * from "fails now", which is precisely the confusion §124 exists to avoid.
 * The history of attempts is not lost: it lives in the CHANGELOG, in the
 * defect records, and in the iteration chain of run records.
 *
 * Everything else is append-only, because a fault that was injected, an
 * audit that was taken, and a human who intervened are facts about the past
 * that no later run may quietly revise.
 */

const ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

function assertRecordId(kind: string, id: string): string {
  if (!ID_PATTERN.test(id)) {
    throw new OrchestrationError('SBO052', `Invalid ${kind} id "${id}".`, {
      remediation: [
        'Ids are generated by SpecBridge; pass one returned by a qualification operation.',
      ],
    });
  }
  return id;
}

export function qualificationDir(workspace: WorkspaceInfo): string {
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(workspace.rootDir, '.specbridge', 'qualification'),
  );
}

export function dogfoodRunDir(workspace: WorkspaceInfo, runId: string): string {
  assertRecordId('dogfood run', runId);
  return assertInsideWorkspace(workspace.rootDir, path.join(qualificationDir(workspace), runId));
}

function runFile(workspace: WorkspaceInfo, runId: string): string {
  return assertInsideWorkspace(workspace.rootDir, path.join(dogfoodRunDir(workspace, runId), 'run.json'));
}

function recordDir(workspace: WorkspaceInfo, runId: string, kind: string): string {
  return assertInsideWorkspace(workspace.rootDir, path.join(dogfoodRunDir(workspace, runId), kind));
}

function recordFile(workspace: WorkspaceInfo, runId: string, kind: string, id: string): string {
  assertRecordId(kind, id);
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(recordDir(workspace, runId, kind), `${id}.json`),
  );
}

function writeRecord(file: string, value: unknown): void {
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(value, null, 2)}\n`);
}

function readRecord<T>(file: string, parse: (raw: unknown) => T): T | undefined {
  if (!existsSync(file)) return undefined;
  try {
    return parse(JSON.parse(readFileSync(file, 'utf8')));
  } catch {
    // A corrupt qualification record must not take down the report that
    // exists to explain the run: it is skipped, left on disk, and shows up
    // as a missing result rather than as a crash.
    return undefined;
  }
}

function listRecords<T>(
  workspace: WorkspaceInfo,
  runId: string,
  kind: string,
  parse: (raw: unknown) => T,
): T[] {
  const dir = recordDir(workspace, runId, kind);
  if (!existsSync(dir)) return [];
  const records: T[] = [];
  for (const entry of readdirSync(dir).sort()) {
    if (!entry.endsWith('.json')) continue;
    const record = readRecord(path.join(dir, entry), parse);
    if (record !== undefined) records.push(record);
  }
  return records;
}

// ---------------------------------------------------------------------------
// Runs
// ---------------------------------------------------------------------------

export function writeDogfoodRun(workspace: WorkspaceInfo, run: DogfoodRun): DogfoodRun {
  const parsed = dogfoodRunSchema.parse(run);
  writeRecord(runFile(workspace, parsed.runId), parsed);
  return parsed;
}

export function readDogfoodRun(workspace: WorkspaceInfo, runId: string): DogfoodRun | undefined {
  return readRecord(runFile(workspace, runId), (raw) => dogfoodRunSchema.parse(raw));
}

export function requireDogfoodRun(workspace: WorkspaceInfo, runId: string): DogfoodRun {
  const run = readDogfoodRun(workspace, runId);
  if (run === undefined) {
    throw new OrchestrationError('SBO053', `Qualification run "${runId}" was not found.`, {
      remediation: [
        'List runs with `specbridge orchestrate qualify runs`.',
        'Start a run with `specbridge orchestrate qualify run`.',
      ],
    });
  }
  return run;
}

/** Every run in the workspace, newest first. Corrupt records are skipped. */
export function listDogfoodRuns(workspace: WorkspaceInfo): DogfoodRun[] {
  const dir = qualificationDir(workspace);
  if (!existsSync(dir)) return [];
  const runs: DogfoodRun[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (!ID_PATTERN.test(entry.name)) continue;
    const run = readDogfoodRun(workspace, entry.name);
    if (run !== undefined) runs.push(run);
  }
  return runs.sort((a, b) => b.startedAt.localeCompare(a.startedAt));
}

// ---------------------------------------------------------------------------
// Scenario results
// ---------------------------------------------------------------------------

export function writeScenarioResult(
  workspace: WorkspaceInfo,
  result: ScenarioResult,
): ScenarioResult {
  const parsed = scenarioResultSchema.parse(result);
  writeRecord(recordFile(workspace, parsed.runId, 'scenarios', parsed.scenarioId), parsed);
  return parsed;
}

export function readScenarioResult(
  workspace: WorkspaceInfo,
  runId: string,
  scenarioId: string,
): ScenarioResult | undefined {
  return readRecord(recordFile(workspace, runId, 'scenarios', scenarioId), (raw) =>
    scenarioResultSchema.parse(raw),
  );
}

export function listScenarioResults(workspace: WorkspaceInfo, runId: string): ScenarioResult[] {
  return listRecords(workspace, runId, 'scenarios', (raw) => scenarioResultSchema.parse(raw));
}

// ---------------------------------------------------------------------------
// Fault injections
// ---------------------------------------------------------------------------

export function writeFaultInjection(
  workspace: WorkspaceInfo,
  record: FaultInjectionRecord,
): FaultInjectionRecord {
  const parsed = faultInjectionRecordSchema.parse(record);
  writeRecord(recordFile(workspace, parsed.runId, 'faults', parsed.faultId), parsed);
  return parsed;
}

export function listFaultInjections(
  workspace: WorkspaceInfo,
  runId: string,
): FaultInjectionRecord[] {
  return listRecords(workspace, runId, 'faults', (raw) => faultInjectionRecordSchema.parse(raw));
}

// ---------------------------------------------------------------------------
// Invariant audits
// ---------------------------------------------------------------------------

export function writeInvariantAudit(
  workspace: WorkspaceInfo,
  audit: InvariantAudit,
): InvariantAudit {
  const parsed = invariantAuditSchema.parse(audit);
  writeRecord(recordFile(workspace, parsed.runId, 'audits', parsed.auditId), parsed);
  return parsed;
}

export function listInvariantAudits(workspace: WorkspaceInfo, runId: string): InvariantAudit[] {
  return listRecords(workspace, runId, 'audits', (raw) => invariantAuditSchema.parse(raw));
}

// ---------------------------------------------------------------------------
// Human interventions
// ---------------------------------------------------------------------------

export function writeHumanIntervention(
  workspace: WorkspaceInfo,
  intervention: HumanIntervention,
): HumanIntervention {
  const parsed = humanInterventionSchema.parse(intervention);
  writeRecord(
    recordFile(workspace, parsed.runId, 'interventions', parsed.interventionId),
    parsed,
  );
  return parsed;
}

export function listHumanInterventions(
  workspace: WorkspaceInfo,
  runId: string,
): HumanIntervention[] {
  return listRecords(workspace, runId, 'interventions', (raw) => humanInterventionSchema.parse(raw));
}

// ---------------------------------------------------------------------------
// Defects
// ---------------------------------------------------------------------------

export function writeDogfoodDefect(
  workspace: WorkspaceInfo,
  defect: DogfoodDefect,
): DogfoodDefect {
  const parsed = dogfoodDefectSchema.parse(defect);
  writeRecord(recordFile(workspace, parsed.runId, 'defects', parsed.defectId), parsed);
  return parsed;
}

export function listDogfoodDefects(workspace: WorkspaceInfo, runId: string): DogfoodDefect[] {
  return listRecords(workspace, runId, 'defects', (raw) => dogfoodDefectSchema.parse(raw));
}

// ---------------------------------------------------------------------------
// Generated artifacts
// ---------------------------------------------------------------------------

const ARTIFACT_NAME_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

/**
 * Write one generated release artifact into the run directory.
 *
 * The name is validated against the same pattern as a record id: report
 * generation must never be a path-traversal surface, even when the caller is
 * the CLI and the name looks like a constant.
 */
export function writeQualificationArtifact(
  workspace: WorkspaceInfo,
  runId: string,
  name: string,
  contents: string,
): string {
  if (!ARTIFACT_NAME_PATTERN.test(name)) {
    throw new OrchestrationError('SBO052', `Invalid qualification artifact name "${name}".`, {
      remediation: ['Artifact names are generated by SpecBridge and contain no path separators.'],
    });
  }
  const file = assertInsideWorkspace(
    workspace.rootDir,
    path.join(recordDir(workspace, runId, 'reports'), name),
  );
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, contents);
  return file;
}

export function qualificationArtifactPath(
  workspace: WorkspaceInfo,
  runId: string,
  name: string,
): string {
  if (!ARTIFACT_NAME_PATTERN.test(name)) {
    throw new OrchestrationError('SBO052', `Invalid qualification artifact name "${name}".`);
  }
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(recordDir(workspace, runId, 'reports'), name),
  );
}
