import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync } from 'node:fs';
import path from 'node:path';
import type { WorkspaceInfo } from '@specbridge/core';
import { assertInsideWorkspace, writeFileAtomic } from '@specbridge/core';
import type {
  ContextEfficiencyMetrics,
  ContextExpansionState,
  ContextSelectionPlan,
  RepositoryContextIndexState,
} from '@specbridge/context';
import {
  contextEfficiencyMetricsSchema,
  contextExpansionStateSchema,
  contextSelectionPlanSchema,
  repositoryContextIndexSchema,
} from '@specbridge/context';
import { OrchestrationError } from '../errors.js';
import { jobDir } from '../jobs/store.js';

/**
 * Context-efficiency persistence.
 *
 *   .specbridge/cache/context-index.json          derived repository index
 *   .specbridge/jobs/<jobId>/context/
 *     expansion/<nodeId>.json                     bounded widening budget
 *     plans/<planId>.json                         selection plans (explain)
 *     metrics/<attemptId>.json                    per-attempt efficiency facts
 *
 * The split between `cache/` and `jobs/` is the whole design in one
 * directory layout:
 *
 *   `cache/` is DISPOSABLE. The repository index is derived from bytes on
 *   disk; deleting it costs a rebuild and nothing else. Job recovery must
 *   never depend on it, which is why it lives outside the job namespace
 *   entirely — a path that makes "delete the cache" an obviously safe
 *   operation rather than a judgement call.
 *
 *   `jobs/<jobId>/context/` is JOB-SCOPED derived state. The expansion budget
 *   has to survive a restart or the bound it enforces would reset every time
 *   a process died — which would turn a bounded widening policy into an
 *   unbounded one. Plans and metrics live beside it for explainability, and
 *   losing any of them degrades diagnostics without touching correctness.
 *
 * Every write is atomic and every path passes `assertInsideWorkspace`, the
 * same discipline the survival and reliability stores already use. Corrupt
 * records are SKIPPED and preserved for diagnosis, never rewritten.
 */

const ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;

function assertRecordId(kind: string, id: string): string {
  if (!ID_PATTERN.test(id)) {
    throw new OrchestrationError('SBO049', `Invalid context ${kind} id "${id}".`, {
      remediation: ['Ids are generated by SpecBridge; pass one returned by a context operation.'],
    });
  }
  return id;
}

// ---------------------------------------------------------------------------
// Repository index cache (disposable)
// ---------------------------------------------------------------------------

export function contextCacheDir(workspace: WorkspaceInfo): string {
  return assertInsideWorkspace(workspace.rootDir, path.join(workspace.sidecarDir, 'cache'));
}

export function repositoryIndexFile(workspace: WorkspaceInfo): string {
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(contextCacheDir(workspace), 'context-index.json'),
  );
}

/**
 * Read the persisted index, or undefined when it is absent, unreadable, or
 * schema-invalid.
 *
 * Every failure mode collapses to the same answer — undefined, meaning
 * "rebuild" — deliberately. There is no state of this file that is worth
 * partially trusting, and a caller that had to distinguish "missing" from
 * "corrupt" would eventually be tempted to use the corrupt one.
 */
export function readRepositoryIndexCache(
  workspace: WorkspaceInfo,
): RepositoryContextIndexState | undefined {
  const file = repositoryIndexFile(workspace);
  if (!existsSync(file)) return undefined;
  try {
    const parsed = repositoryContextIndexSchema.safeParse(JSON.parse(readFileSync(file, 'utf8')));
    return parsed.success ? parsed.data : undefined;
  } catch {
    return undefined;
  }
}

export function writeRepositoryIndexCache(
  workspace: WorkspaceInfo,
  state: RepositoryContextIndexState,
): void {
  const validated = repositoryContextIndexSchema.parse(state);
  const file = repositoryIndexFile(workspace);
  mkdirSync(path.dirname(file), { recursive: true });
  // No pretty-printing: this file is machine state that can hold tens of
  // thousands of entries, and indentation would triple it for nobody.
  writeFileAtomic(file, `${JSON.stringify(validated)}\n`);
}

/** Delete the derived index. Always safe: job state never depends on it. */
export function clearRepositoryIndexCache(workspace: WorkspaceInfo): void {
  const file = repositoryIndexFile(workspace);
  if (existsSync(file)) rmSync(file, { force: true });
}

// ---------------------------------------------------------------------------
// Job-scoped context state
// ---------------------------------------------------------------------------

export function jobContextDir(workspace: WorkspaceInfo, jobId: string): string {
  return assertInsideWorkspace(workspace.rootDir, path.join(jobDir(workspace, jobId), 'context'));
}

function expansionFile(workspace: WorkspaceInfo, jobId: string, nodeId: string): string {
  assertRecordId('node', nodeId);
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(jobContextDir(workspace, jobId), 'expansion', `${nodeId}.json`),
  );
}

export function readContextExpansionState(
  workspace: WorkspaceInfo,
  jobId: string,
  nodeId: string,
): ContextExpansionState | undefined {
  const file = expansionFile(workspace, jobId, nodeId);
  if (!existsSync(file)) return undefined;
  try {
    const parsed = contextExpansionStateSchema.safeParse(JSON.parse(readFileSync(file, 'utf8')));
    return parsed.success ? parsed.data : undefined;
  } catch {
    return undefined;
  }
}

export function writeContextExpansionState(
  workspace: WorkspaceInfo,
  jobId: string,
  nodeId: string,
  state: ContextExpansionState,
): ContextExpansionState {
  const validated = contextExpansionStateSchema.parse(state);
  const file = expansionFile(workspace, jobId, nodeId);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return validated;
}

function planFile(workspace: WorkspaceInfo, jobId: string, planId: string): string {
  assertRecordId('plan', planId);
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(jobContextDir(workspace, jobId), 'plans', `${planId}.json`),
  );
}

/**
 * Persist a selection plan for explainability.
 *
 * The plan carries paths, hashes, ranges, and reasons — never file bodies
 * (see `ContextSelectionPlan`). That is what makes this record safe to keep
 * and safe to print, and it is why the store does not need its own redaction
 * pass: there is nothing here to redact.
 */
export function writeContextSelectionPlan(
  workspace: WorkspaceInfo,
  plan: ContextSelectionPlan,
): ContextSelectionPlan {
  const validated = contextSelectionPlanSchema.parse(plan);
  if (validated.jobId === undefined) return validated;
  const file = planFile(workspace, validated.jobId, validated.planId);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return validated;
}

export function readContextSelectionPlan(
  workspace: WorkspaceInfo,
  jobId: string,
  planId: string,
): ContextSelectionPlan | undefined {
  const file = planFile(workspace, jobId, planId);
  if (!existsSync(file)) return undefined;
  try {
    const parsed = contextSelectionPlanSchema.safeParse(JSON.parse(readFileSync(file, 'utf8')));
    return parsed.success ? parsed.data : undefined;
  } catch {
    return undefined;
  }
}

export interface ListContextPlansOptions {
  nodeId?: string | undefined;
  attemptId?: string | undefined;
}

/** Selection plans for a job, oldest first. Corrupt records are skipped. */
export function listContextSelectionPlans(
  workspace: WorkspaceInfo,
  jobId: string,
  options: ListContextPlansOptions = {},
): ContextSelectionPlan[] {
  const dir = path.join(jobContextDir(workspace, jobId), 'plans');
  if (!existsSync(dir)) return [];
  const plans: ContextSelectionPlan[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith('.json')) continue;
    try {
      const parsed = contextSelectionPlanSchema.safeParse(
        JSON.parse(readFileSync(path.join(dir, entry.name), 'utf8')),
      );
      if (!parsed.success) continue;
      if (options.nodeId !== undefined && parsed.data.nodeId !== options.nodeId) continue;
      if (options.attemptId !== undefined && parsed.data.attemptId !== options.attemptId) continue;
      plans.push(parsed.data);
    } catch {
      continue;
    }
  }
  return plans.sort((left, right) =>
    left.createdAt === right.createdAt
      ? left.planId < right.planId
        ? -1
        : 1
      : left.createdAt < right.createdAt
        ? -1
        : 1,
  );
}

function metricsFile(workspace: WorkspaceInfo, jobId: string, attemptId: string): string {
  assertRecordId('attempt', attemptId);
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(jobContextDir(workspace, jobId), 'metrics', `${attemptId}.json`),
  );
}

export function writeContextMetrics(
  workspace: WorkspaceInfo,
  jobId: string,
  attemptId: string,
  metrics: ContextEfficiencyMetrics,
): ContextEfficiencyMetrics {
  const validated = contextEfficiencyMetricsSchema.parse(metrics);
  const file = metricsFile(workspace, jobId, attemptId);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return validated;
}

export function readContextMetrics(
  workspace: WorkspaceInfo,
  jobId: string,
  attemptId: string,
): ContextEfficiencyMetrics | undefined {
  const file = metricsFile(workspace, jobId, attemptId);
  if (!existsSync(file)) return undefined;
  try {
    const parsed = contextEfficiencyMetricsSchema.safeParse(JSON.parse(readFileSync(file, 'utf8')));
    return parsed.success ? parsed.data : undefined;
  } catch {
    return undefined;
  }
}

/**
 * Every recorded context metric for a job with the attempt it served,
 * oldest first.
 *
 * The attempt id is the FILE NAME, not a field inside the record, so a
 * caller that needs to join metrics onto attempts (vNext.8 does, to price
 * context per verified completion) cannot recover it from `listContextMetrics`
 * alone. Exposed here rather than duplicating the directory walk in the
 * adaptive layer, and returning a pair rather than mutating the metrics
 * shape, which is a published contract.
 */
export function listContextMetricEntries(
  workspace: WorkspaceInfo,
  jobId: string,
): { attemptId: string; metrics: ContextEfficiencyMetrics }[] {
  const dir = path.join(jobContextDir(workspace, jobId), 'metrics');
  if (!existsSync(dir)) return [];
  const records: { attemptId: string; metrics: ContextEfficiencyMetrics }[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith('.json')) continue;
    try {
      const parsed = contextEfficiencyMetricsSchema.safeParse(
        JSON.parse(readFileSync(path.join(dir, entry.name), 'utf8')),
      );
      if (parsed.success) {
        records.push({ attemptId: entry.name.slice(0, -'.json'.length), metrics: parsed.data });
      }
    } catch {
      continue;
    }
  }
  return records.sort((left, right) =>
    left.metrics.createdAt < right.metrics.createdAt ? -1 : 1,
  );
}

/** Every recorded context metric for a job, oldest first. */
export function listContextMetrics(
  workspace: WorkspaceInfo,
  jobId: string,
): ContextEfficiencyMetrics[] {
  const dir = path.join(jobContextDir(workspace, jobId), 'metrics');
  if (!existsSync(dir)) return [];
  const records: ContextEfficiencyMetrics[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith('.json')) continue;
    try {
      const parsed = contextEfficiencyMetricsSchema.safeParse(
        JSON.parse(readFileSync(path.join(dir, entry.name), 'utf8')),
      );
      if (parsed.success) records.push(parsed.data);
    } catch {
      continue;
    }
  }
  return records.sort((left, right) => (left.createdAt < right.createdAt ? -1 : 1));
}
