import { appendFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';
import type { Diagnostic, WorkspaceInfo } from '@specbridge/core';
import { assertInsideWorkspace, sha256Hex, writeFileAtomic } from '@specbridge/core';
import { OrchestrationError } from './errors.js';
import type {
  ExecutionPlan,
  OrchestrationCheckpoint,
  OrchestrationState,
} from './state.js';
import {
  ORCHESTRATION_STATE_SCHEMA_VERSION,
  executionPlanSchema,
  orchestrationCheckpointSchema,
  orchestrationStateSchema,
} from './state.js';
import type { OrchestrationEventType } from './vocabulary.js';

/**
 * Orchestration persistence: `.specbridge/orchestration/<id>/`.
 *
 *   state.json          the versioned state record (atomic, last-writer view)
 *   events.jsonl        append-only history
 *   plans/<n>.json      every plan revision, kept forever
 *   checkpoint.json     the latest structured checkpoint
 *
 * This is a sidecar *referenced from* the existing run model rather than a
 * second run system: each interactive execution run this orchestration drives
 * is an ordinary `.specbridge/runs/<run-id>/` record, and the orchestration
 * state simply holds their ids. Evidence, verification, and completion stay
 * exactly where they already live.
 *
 * Guarantees, all exercised by tests:
 *   - every path passes assertInsideWorkspace (no traversal, no symlink escape)
 *   - every state/plan/checkpoint write is atomic (temp + fsync + rename)
 *   - a corrupt or unknown-major-version record fails safely and is preserved
 *     for diagnosis, never silently rewritten or deleted
 *   - reads never mutate state
 */

export const ORCHESTRATION_DIR_NAME = 'orchestration';

/** Ids are generated by SpecBridge; the pattern is enforced on every path. */
const ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

export function orchestrationRootDir(workspace: WorkspaceInfo): string {
  return path.join(workspace.sidecarDir, ORCHESTRATION_DIR_NAME);
}

export function assertOrchestrationId(orchestrationId: string): string {
  if (!ID_PATTERN.test(orchestrationId)) {
    throw new OrchestrationError('SBO003', `Invalid orchestration id "${orchestrationId}".`, {
      remediation: ['Ids are generated by SpecBridge; pass one returned by an orchestration tool.'],
    });
  }
  return orchestrationId;
}

export function orchestrationDir(workspace: WorkspaceInfo, orchestrationId: string): string {
  assertOrchestrationId(orchestrationId);
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(orchestrationRootDir(workspace), orchestrationId),
  );
}

function artifactPath(
  workspace: WorkspaceInfo,
  orchestrationId: string,
  ...segments: string[]
): string {
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(orchestrationDir(workspace, orchestrationId), ...segments),
  );
}

/** SHA-256 over the canonical serialization of a plan (review binding). */
export function planHash(plan: ExecutionPlan): string {
  return sha256Hex(JSON.stringify(plan)).slice(0, 32);
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

function majorOf(version: string): string {
  return version.split('.')[0] ?? '';
}

export type StateReadResult =
  | { kind: 'ok'; state: OrchestrationState }
  | { kind: 'missing' }
  /** Present but unusable. The file is left exactly as found. */
  | { kind: 'corrupt'; problem: string; file: string }
  | { kind: 'unsupported-version'; version: string; file: string };

export function readOrchestrationState(
  workspace: WorkspaceInfo,
  orchestrationId: string,
): StateReadResult {
  const file = artifactPath(workspace, orchestrationId, 'state.json');
  if (!existsSync(file)) return { kind: 'missing' };
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(file, 'utf8'));
  } catch (cause) {
    return {
      kind: 'corrupt',
      problem: cause instanceof Error ? cause.message : String(cause),
      file,
    };
  }
  const declared =
    parsed !== null && typeof parsed === 'object'
      ? (parsed as { schemaVersion?: unknown }).schemaVersion
      : undefined;
  if (typeof declared !== 'string') {
    return { kind: 'corrupt', problem: 'schemaVersion is missing', file };
  }
  // A future MAJOR version is refused rather than coerced: forward
  // compatibility is a promise we can only keep within a major line.
  if (majorOf(declared) !== majorOf(ORCHESTRATION_STATE_SCHEMA_VERSION)) {
    return { kind: 'unsupported-version', version: declared, file };
  }
  const result = orchestrationStateSchema.safeParse(parsed);
  if (!result.success) {
    return {
      kind: 'corrupt',
      problem: result.error.issues
        .map((issue) => `${issue.path.join('.') || '(root)'}: ${issue.message}`)
        .join('; '),
      file,
    };
  }
  return { kind: 'ok', state: result.data };
}

/** Read state or throw a stable SBO error explaining exactly what is wrong. */
export function requireOrchestrationState(
  workspace: WorkspaceInfo,
  orchestrationId: string,
): OrchestrationState {
  const read = readOrchestrationState(workspace, orchestrationId);
  switch (read.kind) {
    case 'ok':
      return read.state;
    case 'missing':
      throw new OrchestrationError(
        'SBO002',
        `Orchestration run "${orchestrationId}" was not found under .specbridge/${ORCHESTRATION_DIR_NAME}/.`,
        { remediation: ['List runs with `specbridge orchestrate status --json`.'] },
      );
    case 'corrupt':
      throw new OrchestrationError(
        'SBO003',
        `Orchestration run "${orchestrationId}" has unreadable state: ${read.problem}. ` +
          'The file was left untouched for diagnosis.',
        {
          remediation: [
            `Inspect ${read.file}.`,
            'Start a new orchestration run; the corrupt record is never rewritten automatically.',
          ],
          details: { file: read.file },
        },
      );
    case 'unsupported-version':
      throw new OrchestrationError(
        'SBO003',
        `Orchestration run "${orchestrationId}" was written by a newer SpecBridge ` +
          `(state schema ${read.version}); this build reads ${ORCHESTRATION_STATE_SCHEMA_VERSION}.`,
        {
          remediation: ['Upgrade SpecBridge, or start a new run with this version.'],
          details: { file: read.file, version: read.version },
        },
      );
  }
}

export function writeOrchestrationState(
  workspace: WorkspaceInfo,
  state: OrchestrationState,
): OrchestrationState {
  const validated = orchestrationStateSchema.parse(state);
  const dir = orchestrationDir(workspace, validated.orchestrationId);
  mkdirSync(dir, { recursive: true });
  writeFileAtomic(path.join(dir, 'state.json'), `${JSON.stringify(validated, null, 2)}\n`);
  return validated;
}

export function createOrchestrationRun(
  workspace: WorkspaceInfo,
  state: OrchestrationState,
): OrchestrationState {
  const dir = orchestrationDir(workspace, state.orchestrationId);
  if (existsSync(dir)) {
    throw new OrchestrationError(
      'SBO003',
      `Orchestration directory already exists: ${dir}. Ids must be unique.`,
    );
  }
  mkdirSync(path.join(dir, 'plans'), { recursive: true });
  return writeOrchestrationState(workspace, state);
}

export interface OrchestrationListResult {
  runs: OrchestrationState[];
  diagnostics: Diagnostic[];
}

/** All orchestration runs, newest first. Unreadable records become diagnostics. */
export function listOrchestrationRuns(workspace: WorkspaceInfo): OrchestrationListResult {
  const root = orchestrationRootDir(workspace);
  if (!existsSync(root)) return { runs: [], diagnostics: [] };
  const runs: OrchestrationState[] = [];
  const diagnostics: Diagnostic[] = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (!ID_PATTERN.test(entry.name)) continue;
    const read = readOrchestrationState(workspace, entry.name);
    if (read.kind === 'ok') {
      runs.push(read.state);
      continue;
    }
    if (read.kind === 'missing') continue;
    diagnostics.push({
      severity: 'warning',
      code:
        read.kind === 'unsupported-version'
          ? 'ORCHESTRATION_STATE_UNSUPPORTED_VERSION'
          : 'ORCHESTRATION_STATE_UNREADABLE',
      message:
        read.kind === 'unsupported-version'
          ? `Orchestration run ${entry.name} uses state schema ${read.version}; ignoring it.`
          : `Orchestration run ${entry.name} has unreadable state; ignoring it.`,
      file: read.file,
    });
  }
  runs.sort(
    (a, b) =>
      b.createdAt.localeCompare(a.createdAt, 'en') ||
      b.orchestrationId.localeCompare(a.orchestrationId, 'en'),
  );
  return { runs, diagnostics };
}

// ---------------------------------------------------------------------------
// Plans
// ---------------------------------------------------------------------------

/** Persist one plan revision. Revisions are append-only: nothing is replaced. */
export function storePlanRevision(
  workspace: WorkspaceInfo,
  orchestrationId: string,
  plan: ExecutionPlan,
): { plan: ExecutionPlan; hash: string; file: string } {
  const validated = executionPlanSchema.parse(plan);
  const file = artifactPath(
    workspace,
    orchestrationId,
    'plans',
    `${String(validated.revision).padStart(4, '0')}.json`,
  );
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return { plan: validated, hash: planHash(validated), file };
}

export function readPlanRevision(
  workspace: WorkspaceInfo,
  orchestrationId: string,
  revision: number,
): ExecutionPlan | undefined {
  if (!Number.isInteger(revision) || revision < 1) return undefined;
  const file = artifactPath(
    workspace,
    orchestrationId,
    'plans',
    `${String(revision).padStart(4, '0')}.json`,
  );
  if (!existsSync(file)) return undefined;
  try {
    const result = executionPlanSchema.safeParse(JSON.parse(readFileSync(file, 'utf8')));
    return result.success ? result.data : undefined;
  } catch {
    return undefined;
  }
}

/** Every stored plan revision, oldest first (bounded by the caller). */
export function listPlanRevisions(
  workspace: WorkspaceInfo,
  orchestrationId: string,
): ExecutionPlan[] {
  const dir = artifactPath(workspace, orchestrationId, 'plans');
  if (!existsSync(dir)) return [];
  const plans: ExecutionPlan[] = [];
  for (const name of readdirSync(dir).sort()) {
    if (!/^\d{4}\.json$/.test(name)) continue;
    const revision = Number.parseInt(name.slice(0, 4), 10);
    const plan = readPlanRevision(workspace, orchestrationId, revision);
    if (plan !== undefined) plans.push(plan);
  }
  return plans;
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

export interface OrchestrationEvent extends Record<string, unknown> {
  at: string;
  type: OrchestrationEventType;
}

/**
 * Append one bounded event. Oversized payloads are refused rather than
 * truncated: a silently trimmed audit record is worse than a rejected one.
 */
export function appendOrchestrationEvent(
  workspace: WorkspaceInfo,
  orchestrationId: string,
  event: OrchestrationEvent,
  limits: { maxEventBytes: number },
): void {
  const line = `${JSON.stringify(event)}\n`;
  if (Buffer.byteLength(line, 'utf8') > limits.maxEventBytes) {
    throw new OrchestrationError(
      'SBO021',
      `Orchestration event of type "${event.type}" is larger than the configured ` +
        `${limits.maxEventBytes}-byte limit and was not recorded.`,
      { remediation: ['Record a shorter summary; full evidence lives in the run directory.'] },
    );
  }
  const file = artifactPath(workspace, orchestrationId, 'events.jsonl');
  mkdirSync(path.dirname(file), { recursive: true });
  appendFileSync(file, line, 'utf8');
}

export interface EventPage {
  events: OrchestrationEvent[];
  total: number;
  truncated: boolean;
}

/**
 * Read a bounded page of events, newest last.
 *
 * History is persisted in full but never returned in full by default: an
 * append-only log must not be able to produce an unbounded response.
 */
export function readOrchestrationEvents(
  workspace: WorkspaceInfo,
  orchestrationId: string,
  options: { limit?: number; offset?: number } = {},
): EventPage {
  const file = artifactPath(workspace, orchestrationId, 'events.jsonl');
  if (!existsSync(file)) return { events: [], total: 0, truncated: false };
  let raw: string;
  try {
    raw = readFileSync(file, 'utf8');
  } catch {
    return { events: [], total: 0, truncated: false };
  }
  const lines = raw.split('\n').filter((line) => line.trim().length > 0);
  const parsed: OrchestrationEvent[] = [];
  for (const line of lines) {
    try {
      const value: unknown = JSON.parse(line);
      if (value !== null && typeof value === 'object') parsed.push(value as OrchestrationEvent);
    } catch {
      // A partially written final line (crash during append) is skipped, not
      // fatal: the rest of the history stays readable.
    }
  }
  const limit = Math.max(1, Math.min(options.limit ?? 50, 500));
  const offset = Math.max(0, options.offset ?? 0);
  const window = parsed.slice(Math.max(0, parsed.length - offset - limit), parsed.length - offset);
  return { events: window, total: parsed.length, truncated: parsed.length > window.length };
}

export function countOrchestrationEvents(
  workspace: WorkspaceInfo,
  orchestrationId: string,
): number {
  const file = artifactPath(workspace, orchestrationId, 'events.jsonl');
  if (!existsSync(file)) return 0;
  try {
    // Counting newlines avoids materializing every parsed event.
    return readFileSync(file, 'utf8').split('\n').filter((line) => line.trim().length > 0).length;
  } catch {
    return 0;
  }
}

// ---------------------------------------------------------------------------
// Checkpoints
// ---------------------------------------------------------------------------

export function writeOrchestrationCheckpoint(
  workspace: WorkspaceInfo,
  orchestrationId: string,
  checkpoint: OrchestrationCheckpoint,
): string {
  const validated = orchestrationCheckpointSchema.parse(checkpoint);
  const file = artifactPath(workspace, orchestrationId, 'checkpoint.json');
  writeFileAtomic(file, `${JSON.stringify(validated, null, 2)}\n`);
  return file;
}

export function readOrchestrationCheckpoint(
  workspace: WorkspaceInfo,
  orchestrationId: string,
): OrchestrationCheckpoint | undefined {
  const file = artifactPath(workspace, orchestrationId, 'checkpoint.json');
  if (!existsSync(file)) return undefined;
  try {
    const result = orchestrationCheckpointSchema.safeParse(JSON.parse(readFileSync(file, 'utf8')));
    return result.success ? result.data : undefined;
  } catch {
    return undefined;
  }
}

/** Total bytes stored for one orchestration run (bounds reporting). */
export function orchestrationStorageBytes(
  workspace: WorkspaceInfo,
  orchestrationId: string,
): number {
  const dir = orchestrationDir(workspace, orchestrationId);
  if (!existsSync(dir)) return 0;
  let total = 0;
  const walk = (current: string): void => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const child = path.join(current, entry.name);
      if (entry.isDirectory()) {
        walk(child);
      } else if (entry.isFile()) {
        try {
          total += statSync(child).size;
        } catch {
          // Concurrent removal is not an error for a size report.
        }
      }
    }
  };
  walk(dir);
  return total;
}
