import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync } from 'node:fs';
import path from 'node:path';
import type { WorkspaceInfo } from '@specbridge/core';
import { assertInsideWorkspace, writeFileAtomic } from '@specbridge/core';
import { OrchestrationError } from '../errors.js';
import { jobDir } from '../jobs/store.js';
import type {
  EvaluationResult,
  FailureAssessment,
  RecoveryDecision,
  TaskReliabilityState,
} from './state.js';
import {
  TASK_RELIABILITY_SCHEMA_VERSION,
  evaluationResultSchema,
  failureAssessmentSchema,
  recoveryDecisionSchema,
  taskReliabilityStateSchema,
} from './state.js';

/**
 * Reliability persistence, inside the existing job namespace:
 *
 *   .specbridge/jobs/<jobId>/reliability/
 *     evaluations/<evaluationId>.json    durable verdicts on attempts
 *     assessments/<assessmentId>.json    durable failure assessments
 *     decisions/<decisionId>.json        durable recovery decisions
 *     tasks/<nodeId>.json                bounded per-task health + history
 *
 * Same guarantees as every other job artifact, and for the same reasons:
 *   - every path passes assertInsideWorkspace
 *   - every write is atomic (temp + fsync + rename)
 *   - evaluations, assessments, and decisions are append-only records
 *   - a corrupt record is skipped by listings and preserved for diagnosis
 *
 * The per-task state file is the one mutable record, and deliberately so:
 *   it is a BOUNDED rolling window plus cumulative counters, so it cannot
 *   grow without limit on a long-horizon task. Its history is derivable from
 *   the append-only records if it were ever lost.
 *
 * Why a separate directory rather than fields on the job state: a recovery
 * decision must survive a crash that happens between deciding and acting.
 * Writing it as its own atomic file means the decision is durable the
 * instant it is made, without having to rewrite (and risk) the job state
 * that the next process needs in order to recover at all.
 */

const ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

function assertRecordId(kind: string, id: string): string {
  if (!ID_PATTERN.test(id)) {
    throw new OrchestrationError('SBO049', `Invalid ${kind} id "${id}".`, {
      remediation: ['Ids are generated by SpecBridge; pass one returned by a reliability operation.'],
    });
  }
  return id;
}

export function reliabilityDir(workspace: WorkspaceInfo, jobId: string): string {
  return assertInsideWorkspace(workspace.rootDir, path.join(jobDir(workspace, jobId), 'reliability'));
}

function recordDir(workspace: WorkspaceInfo, jobId: string, kind: string): string {
  return assertInsideWorkspace(workspace.rootDir, path.join(reliabilityDir(workspace, jobId), kind));
}

function recordFile(workspace: WorkspaceInfo, jobId: string, kind: string, id: string): string {
  assertRecordId(kind, id);
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(recordDir(workspace, jobId, kind), `${id}.json`),
  );
}

function writeRecord(file: string, value: unknown): void {
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileAtomic(file, `${JSON.stringify(value, null, 2)}\n`);
}

function readRecord<T>(file: string, parse: (raw: unknown) => T): T | undefined {
  if (!existsSync(file)) return undefined;
  try {
    return parse(JSON.parse(readFileSync(file, 'utf8')));
  } catch {
    // A corrupt record is preserved for diagnosis, never rewritten and never
    // allowed to take down a listing: reliability state exists to explain
    // failures, so it must not become one.
    return undefined;
  }
}

function listRecords<T>(
  workspace: WorkspaceInfo,
  jobId: string,
  kind: string,
  parse: (raw: unknown) => T,
): T[] {
  const dir = recordDir(workspace, jobId, kind);
  if (!existsSync(dir)) return [];
  const records: T[] = [];
  for (const entry of readdirSync(dir).sort()) {
    if (!entry.endsWith('.json')) continue;
    const record = readRecord(path.join(dir, entry), parse);
    if (record !== undefined) records.push(record);
  }
  return records;
}

/**
 * Prune the oldest records of one kind past the configured ceiling.
 *
 * Ids are time-ordered by construction, so lexical sort is chronological.
 * Pruning is bounded maintenance, not history rewriting: what is removed is
 * old detail, and every surviving record keeps its exact contents.
 */
function pruneRecords(workspace: WorkspaceInfo, jobId: string, kind: string, max: number): void {
  const dir = recordDir(workspace, jobId, kind);
  if (!existsSync(dir)) return;
  const files = readdirSync(dir)
    .filter((entry) => entry.endsWith('.json'))
    .sort();
  if (files.length <= max) return;
  for (const stale of files.slice(0, files.length - max)) {
    try {
      rmSync(path.join(dir, stale), { force: true });
    } catch {
      // Pruning is best-effort maintenance; a locked file is not an error.
    }
  }
}

// ---------------------------------------------------------------------------
// Evaluations
// ---------------------------------------------------------------------------

export function writeEvaluationResult(
  workspace: WorkspaceInfo,
  result: EvaluationResult,
  options: { maxRecords?: number } = {},
): EvaluationResult {
  const validated = evaluationResultSchema.parse(result);
  writeRecord(
    recordFile(workspace, validated.jobId, 'evaluations', validated.evaluationId),
    validated,
  );
  if (options.maxRecords !== undefined) {
    pruneRecords(workspace, validated.jobId, 'evaluations', options.maxRecords);
  }
  return validated;
}

export function readEvaluationResult(
  workspace: WorkspaceInfo,
  jobId: string,
  evaluationId: string,
): EvaluationResult | undefined {
  return readRecord(recordFile(workspace, jobId, 'evaluations', evaluationId), (raw) =>
    evaluationResultSchema.parse(raw),
  );
}

export function listEvaluationResults(
  workspace: WorkspaceInfo,
  jobId: string,
  filter: { nodeId?: string } = {},
): EvaluationResult[] {
  const all = listRecords(workspace, jobId, 'evaluations', (raw) => evaluationResultSchema.parse(raw));
  return filter.nodeId === undefined ? all : all.filter((entry) => entry.nodeId === filter.nodeId);
}

// ---------------------------------------------------------------------------
// Assessments
// ---------------------------------------------------------------------------

export function writeFailureAssessment(
  workspace: WorkspaceInfo,
  assessment: FailureAssessment,
  options: { maxRecords?: number } = {},
): FailureAssessment {
  const validated = failureAssessmentSchema.parse(assessment);
  writeRecord(
    recordFile(workspace, validated.jobId, 'assessments', validated.assessmentId),
    validated,
  );
  if (options.maxRecords !== undefined) {
    pruneRecords(workspace, validated.jobId, 'assessments', options.maxRecords);
  }
  return validated;
}

export function listFailureAssessments(
  workspace: WorkspaceInfo,
  jobId: string,
  filter: { nodeId?: string } = {},
): FailureAssessment[] {
  const all = listRecords(workspace, jobId, 'assessments', (raw) =>
    failureAssessmentSchema.parse(raw),
  );
  return filter.nodeId === undefined ? all : all.filter((entry) => entry.nodeId === filter.nodeId);
}

// ---------------------------------------------------------------------------
// Recovery decisions
// ---------------------------------------------------------------------------

export function writeRecoveryDecision(
  workspace: WorkspaceInfo,
  decision: RecoveryDecision,
  options: { maxRecords?: number } = {},
): RecoveryDecision {
  const validated = recoveryDecisionSchema.parse(decision);
  writeRecord(recordFile(workspace, validated.jobId, 'decisions', validated.decisionId), validated);
  if (options.maxRecords !== undefined) {
    pruneRecords(workspace, validated.jobId, 'decisions', options.maxRecords);
  }
  return validated;
}

export function readRecoveryDecision(
  workspace: WorkspaceInfo,
  jobId: string,
  decisionId: string,
): RecoveryDecision | undefined {
  return readRecord(recordFile(workspace, jobId, 'decisions', decisionId), (raw) =>
    recoveryDecisionSchema.parse(raw),
  );
}

export function listRecoveryDecisions(
  workspace: WorkspaceInfo,
  jobId: string,
  filter: { nodeId?: string } = {},
): RecoveryDecision[] {
  const all = listRecords(workspace, jobId, 'decisions', (raw) => recoveryDecisionSchema.parse(raw));
  return filter.nodeId === undefined ? all : all.filter((entry) => entry.nodeId === filter.nodeId);
}

/** Mark a persisted decision as acted upon. Identity and contents are kept. */
export function markRecoveryDecisionApplied(
  workspace: WorkspaceInfo,
  jobId: string,
  decisionId: string,
): RecoveryDecision | undefined {
  const decision = readRecoveryDecision(workspace, jobId, decisionId);
  if (decision === undefined) return undefined;
  const applied = recoveryDecisionSchema.parse({ ...decision, applied: true });
  writeRecord(recordFile(workspace, jobId, 'decisions', decisionId), applied);
  return applied;
}

// ---------------------------------------------------------------------------
// Per-task reliability state
// ---------------------------------------------------------------------------

function taskStateFile(workspace: WorkspaceInfo, jobId: string, nodeId: string): string {
  assertRecordId('node', nodeId);
  return assertInsideWorkspace(
    workspace.rootDir,
    path.join(recordDir(workspace, jobId, 'tasks'), `${nodeId}.json`),
  );
}

export function readTaskReliabilityState(
  workspace: WorkspaceInfo,
  jobId: string,
  nodeId: string,
): TaskReliabilityState | undefined {
  return readRecord(taskStateFile(workspace, jobId, nodeId), (raw) =>
    taskReliabilityStateSchema.parse(raw),
  );
}

/**
 * Read the task's reliability state, or an empty one.
 *
 * A task with no history is HEALTHY with an empty window — never a missing
 * value the callers would each have to remember to handle. Loop detection
 * over an empty window trivially reports no loop, which is correct.
 */
export function requireTaskReliabilityState(
  workspace: WorkspaceInfo,
  jobId: string,
  nodeId: string,
  taskId: string,
  at: string,
): TaskReliabilityState {
  return (
    readTaskReliabilityState(workspace, jobId, nodeId) ??
    taskReliabilityStateSchema.parse({
      schemaVersion: TASK_RELIABILITY_SCHEMA_VERSION,
      jobId,
      nodeId,
      taskId,
      updatedAt: at,
    })
  );
}

export function writeTaskReliabilityState(
  workspace: WorkspaceInfo,
  state: TaskReliabilityState,
): TaskReliabilityState {
  const validated = taskReliabilityStateSchema.parse(state);
  writeRecord(taskStateFile(workspace, validated.jobId, validated.nodeId), validated);
  return validated;
}

export function listTaskReliabilityStates(
  workspace: WorkspaceInfo,
  jobId: string,
): TaskReliabilityState[] {
  return listRecords(workspace, jobId, 'tasks', (raw) => taskReliabilityStateSchema.parse(raw));
}
